# CityLens Baseline Comparison

Use this notebook for the next experiment phase only:

- lock the current `prithvi_rgb_lora` reference results
- run fair satellite backbone comparisons
- summarize metrics into one table
- decide whether street-only and fusion are worth running next

This notebook is intentionally smaller than `colab_citylens_full.ipynb` and calls the existing training entrypoints instead of duplicating the full pipeline.

## Colab setup

Upload this notebook to a fresh Colab runtime, choose a GPU, then run all cells. This notebook mounts Drive, clones the repo, installs the learned-model dependencies, and runs only the comparison-phase experiments.

In [37]:
!pip install -q virtualenv
!rm -rf /content/citylens_venv
!virtualenv /content/citylens_venv

!/content/citylens_venv/bin/python -m pip install -U pip wheel
!/content/citylens_venv/bin/python -m pip install --no-cache-dir \
  "numpy==1.26.4" "scipy==1.13.1" "scikit-learn==1.5.2" "pandas==2.2.2"

created virtual environment CPython3.12.12.final.0-64-x86_64 in 368ms
  creator CPython3Posix(dest=/content/citylens_venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/root/.cache/virtualenv)
    added seed packages: pip==26.0.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
Requirement already satisfied: pip in ./citylens_venv/lib/python3.12/site-packages (26.0.1)
Collecting wheel
  Using cached wheel-0.46.3-py3-none-any.whl.metadata (2.4 kB)
Collecting packaging>=24.0 (from wheel)
  Using cached packaging-26.0-py3-none-any.whl.metadata (3.3 kB)
Using cached wheel-0.46.3-py3-none-any.whl (30 kB)
Using cached packaging-26.0-py3-none-any.whl (74 kB)
Installing collected packages: packaging, wheel
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [wheel]
Successfully installed packaging-26.0 wheel-0.46.3
Collecting numpy==1.26.4
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Collecting scipy==1.13.1
  Downloading scipy-1.13.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
Collecting scikit-learn==1.5.2
  Downloading scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Collecting pandas==2.2.2
  Downloading pandas-2.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Collecting joblib>=1.2.0 (from scikit-learn==1.5.2)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn==1.5.2)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting python-dateutil>=2.8.2 (from pandas==2.2.2)
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz>=2020.1 (from pandas==2.2.2)
  Downloading pytz-2026.1.post1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas==2.2.2)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas==2.2.2)
  Downloading six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 190.6 MB/s  0:00:00
Downloading scipy-1.13.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.2/38.2 MB 274.3 MB/s  0:00:00
Downloading scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.9/12.9 MB 275.3 MB/s  0:00:00
Downloading pandas-2.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.7/12.7 MB 221.9 MB/s  0:00:00
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Downloading pytz-2026.1.post1-py2.py3-none-any.whl (510 kB)
Downloading six-1.17.0-py2.py3-none-any.whl (11 kB)
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: pytz, tzdata, threadpoolctl, six, numpy, joblib, scipy, python-dateutil, scikit-learn, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10/10 [pandas]
Successfully installed joblib-1.5.3 numpy-1.26.4 pandas-2.2.2 python-dateutil-2.9.0.post0 pytz-2026.1.post1 scikit-learn-1.5.2 scipy-1.13.1 six-1.17.0 threadpoolctl-3.6.0 tzdata-2025.3

In [38]:
from pathlib import Path
import os
import subprocess
import sys

REPO_ROOT = Path('/content/CityLens')
REPO_URL = 'https://github.com/wojackbro/GEOBENCH.git'

if not REPO_ROOT.exists():
    subprocess.run(['git', 'clone', '--depth', '1', REPO_URL, str(REPO_ROOT)], check=True)
else:
    if (REPO_ROOT / '.git').exists():
        subprocess.run(['git', 'fetch', 'origin'], cwd=str(REPO_ROOT), check=True)
        subprocess.run(['git', 'checkout', 'main'], cwd=str(REPO_ROOT), check=True)
        subprocess.run(['git', 'pull', '--ff-only', 'origin', 'main'], cwd=str(REPO_ROOT), check=True)
    else:
        raise SystemExit(f'Expected a git repo at {REPO_ROOT}, but .git is missing.')

# Auto-detect project root (some Colab runs have nested /content/CityLens/CityLens)
CANDIDATE_ROOTS = [REPO_ROOT, REPO_ROOT / 'CityLens']
PROJECT_ROOT = None
for candidate in CANDIDATE_ROOTS:
    if (candidate / 'evaluate' / 'global_learned' / 'train.py').exists():
        PROJECT_ROOT = candidate
        break

if PROJECT_ROOT is None:
    raise SystemExit('Could not locate evaluate/global_learned/train.py after clone/pull.')

commit = subprocess.check_output(['git', 'rev-parse', '--short', 'HEAD'], cwd=str(REPO_ROOT), text=True).strip()
print('Repo root:', REPO_ROOT)
print('Project root:', PROJECT_ROOT)
print('Commit:', commit)

Repo root: /content/CityLens
Project root: /content/CityLens/CityLens
Commit: 319729e

In [39]:
from google.colab import drive
drive.mount('/content/drive')

DATA_ROOT = Path('/content/drive/MyDrive/GeoBench/CityLens-Data/CityLens-data')
os.environ['CITYLENS_DATA_ROOT'] = str(DATA_ROOT)
print('CITYLENS_DATA_ROOT =', os.environ['CITYLENS_DATA_ROOT'])

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
CITYLENS_DATA_ROOT = /content/drive/MyDrive/GeoBench/CityLens-Data/CityLens-data

In [40]:
required = [
    DATA_ROOT / 'Benchmark',
    DATA_ROOT / 'Results',
    PROJECT_ROOT,
    PROJECT_ROOT / 'evaluate' / 'global_learned' / 'train.py',
]
for path in required:
    print(path, 'exists=' + str(path.exists()))

if not (DATA_ROOT / 'Benchmark').exists():
    raise SystemExit('CityLens data not found in Drive. Reuse the previous full notebook once to prepare the dataset first.')
if not (PROJECT_ROOT / 'evaluate' / 'global_learned' / 'train.py').exists():
    raise SystemExit('Project checkout is missing evaluate/global_learned/train.py. Re-run the repo clone/pull cell.')

/content/drive/MyDrive/GeoBench/CityLens-Data/CityLens-data/Benchmark exists=True
/content/drive/MyDrive/GeoBench/CityLens-Data/CityLens-data/Results exists=True
/content/CityLens/CityLens exists=True
/content/CityLens/CityLens/evaluate/global_learned/train.py exists=True

In [41]:
from pathlib import Path
import json
import os
import subprocess
import pandas as pd

DATA_ROOT = Path('/content/drive/MyDrive/GeoBench/CityLens-Data/CityLens-data')
CITYLENS_ROOT = PROJECT_ROOT
RESULTS_ROOT = DATA_ROOT / 'Results' / 'global_learned'

REFERENCE_MODELS = ['prithvi_rgb_lora', 'dinov2_sat', 'resnet50_sat']
TASK_EPOCHS = {
    'gdp': 20,
    'acc2health': 30,
    'build_height': 30,
    'pop': 5,
}

LOCKED_PRITHVI = {
    'gdp': {'r2': 0.5807730555534363, 'rmse': 331463584.0, 'best_epoch': 14, 'epochs': 20},
    'acc2health': {'r2': 0.39014101028442383, 'rmse': 9.55018424987793, 'best_epoch': 9, 'epochs': 30},
    'build_height': {'r2': 0.8681523203849792, 'rmse': 2.534539222717285, 'best_epoch': 9, 'epochs': 30},
    'pop': {'r2': -0.03239285945892334, 'rmse': 21641.24609375, 'best_epoch': 2, 'epochs': 5},
}

COMMON = {
    'branch': 'satellite',
    'street_model': 'clip_vitb16',
    'batch_size': 8,
    'image_size': 224,
    'lr': 2e-4,
    'backbone_lr': 2e-4,
    'head_lr': 1e-3,
    'weight_decay': 1e-2,
    'seed': 42,
    'lora_r': 8,
    'target_transform': 'log1p',
    'val_frac': 0.1,
    'num_workers': 2,
}

assert DATA_ROOT.exists(), f'Missing data root: {DATA_ROOT}'
assert CITYLENS_ROOT.exists(), f'Missing project root: {CITYLENS_ROOT}'
assert (CITYLENS_ROOT / 'evaluate' / 'global_learned' / 'train.py').exists(), 'Missing evaluate/global_learned/train.py in CITYLENS_ROOT'
print('Project root:', CITYLENS_ROOT)
print('Results root:', RESULTS_ROOT)

Project root: /content/CityLens/CityLens
Results root: /content/drive/MyDrive/GeoBench/CityLens-Data/CityLens-data/Results/global_learned

In [42]:
import os
import sys


def run_train(
    task_name: str,
    branch: str,
    epochs: int,
    satellite_model: str = 'prithvi_rgb_lora',
    street_model: str = 'clip_vitb16',
    fusion_type: str = 'late',
    pooling: str = 'mean',
    resume: bool = True,
    skip_if_done: bool = True,
):
    # Build CLI args for argparse (run in-process so Colab shows the real traceback;
    # subprocess + sys.executable often hides errors or uses a different env than the kernel).
    cli = [
        '--task_name', task_name,
        '--branch', branch,
        '--satellite_model', satellite_model,
        '--street_model', street_model,
        '--fusion_type', fusion_type,
        '--pooling', pooling,
        '--epochs', str(epochs),
        '--batch_size', str(COMMON['batch_size']),
        '--image_size', str(COMMON['image_size']),
        '--lr', str(COMMON['lr']),
        '--backbone_lr', str(COMMON['backbone_lr']),
        '--head_lr', str(COMMON['head_lr']),
        '--weight_decay', str(COMMON['weight_decay']),
        '--seed', str(COMMON['seed']),
        '--lora_r', str(COMMON['lora_r']),
        '--target_transform', COMMON['target_transform'],
        '--val_frac', str(COMMON['val_frac']),
        '--num_workers', str(COMMON['num_workers']),
        '--data_root', str(DATA_ROOT),
    ]
    if resume:
        cli.append('--resume')
    if skip_if_done:
        cli.append('--skip_if_done')

    print('\n$ ' + ' '.join([sys.executable, '-m', 'evaluate.global_learned.train'] + cli))

    root = str(CITYLENS_ROOT)
    argv_bak = sys.argv[:]
    cwd_bak = os.getcwd()
    try:
        os.chdir(root)
        if root not in sys.path:
            sys.path.insert(0, root)
        sys.argv = ['evaluate.global_learned.train'] + cli
        from evaluate.global_learned.train import main as _train_main

        _train_main()
    finally:
        sys.argv = argv_bak
        os.chdir(cwd_bak)


def run_satellite_matrix(tasks, models):
    for task_name in tasks:
        epochs = TASK_EPOCHS[task_name]
        for satellite_model in models:
            run_train(task_name, branch='satellite', satellite_model=satellite_model, epochs=epochs)


def run_street_matrix(tasks, street_models):
    for task_name in tasks:
        epochs = TASK_EPOCHS[task_name]
        for street_model in street_models:
            run_train(task_name, branch='street', street_model=street_model, epochs=epochs)


def run_fusion_matrix(tasks, street_models, fusion_types=('late', 'gated'), satellite_model='prithvi_rgb_lora'):
    for task_name in tasks:
        epochs = TASK_EPOCHS[task_name]
        for street_model in street_models:
            for fusion_type in fusion_types:
                run_train(
                    task_name,
                    branch='fusion',
                    satellite_model=satellite_model,
                    street_model=street_model,
                    fusion_type=fusion_type,
                    epochs=epochs,
                )

## Run controls (satellite archived, street/fusion next)

Satellite baseline stage is complete.

Use the run-control cell to choose what runs now:

1. `RUN_SATELLITE=False` (default, avoid re-running completed baselines)
2. `RUN_STREET=True` to launch street-only matrix
3. `RUN_FUSION=True` after street results are ready

Keep `RUN_*` flags `False` for stages you do not want to execute.

In [43]:
from pathlib import Path
import subprocess

def run_street_matrix(tasks, street_models):
    for task_name in tasks:
        epochs = TASK_EPOCHS[task_name]
        for street_model in street_models:
            try:
                run_train(task_name, branch='street', street_model=street_model, epochs=epochs)
            except subprocess.CalledProcessError as e:
                print(f"[SKIP] street/{task_name}/{street_model} failed (likely no records).")

p = Path("/content/CityLens/CityLens/evaluate/global_learned/models.py")
txt = p.read_text()

old = 'self.backbone = timm.create_model(model_name, pretrained=True, num_classes=0)'
new = 'self.backbone = timm.create_model(model_name, pretrained=True, num_classes=0, img_size=224)'

if old in txt and new not in txt:
    txt = txt.replace(old, new)
    p.write_text(txt)
    print("Patched TimmEncoder to force img_size=224")
else:
    print("Patch already applied or line not found")

Patch already applied or line not found

In [44]:
!rg "create_model\(model_name, pretrained=True, num_classes=0, img_size=224\)" /content/CityLens/CityLens/evaluate/global_learned/models.py

39:            self.backbone = timm.create_model(model_name, pretrained=True, num_classes=0, img_size=224)

In [45]:
from pathlib import Path

p = Path("/content/CityLens/CityLens/evaluate/global_learned/utils.py")
txt = p.read_text()

old = "rmse = mean_squared_error(y_true, y_pred, squared=False)"
new = "rmse = float(np.sqrt(mse))"

if old in txt:
    txt = txt.replace(old, new)
    p.write_text(txt)
    print("Patched compute_metrics: rmse now uses sqrt(mse)")
else:
    print("Patch target not found (may already be patched)")

Patch target not found (may already be patched)

In [46]:
!rg "img_size=224" /content/CityLens/CityLens/evaluate/global_learned/models.py

39:            self.backbone = timm.create_model(model_name, pretrained=True, num_classes=0, img_size=224)

In [47]:
!rg "rmse = " /content/CityLens/CityLens/evaluate/global_learned/utils.py

93:    rmse = float(np.sqrt(mse))

In [48]:
from pathlib import Path

p = Path("/content/CityLens/CityLens/evaluate/global_learned/models.py")
txt = p.read_text()

old_block = """        self.backbone = timm.create_model(model_name, pretrained=True, num_classes=0, img_size=224)
        self.feature_dim = getattr(self.backbone, "num_features", None) or getattr(self.backbone, "embed_dim", None)
"""

new_block = """        # Only some timm models (e.g., ViTs) accept img_size in constructor.
        # ResNet and others can fail if img_size is passed.
        if "vit" in model_name or "dinov2" in model_name:
            self.backbone = timm.create_model(model_name, pretrained=True, num_classes=0, img_size=224)
        else:
            self.backbone = timm.create_model(model_name, pretrained=True, num_classes=0)
        self.feature_dim = getattr(self.backbone, "num_features", None) or getattr(self.backbone, "embed_dim", None)
"""

if old_block in txt:
    txt = txt.replace(old_block, new_block)
    p.write_text(txt)
    print("Patched TimmEncoder: img_size only for ViT/DINO models.")
else:
    print("Expected block not found; print constructor section manually and patch by hand.")

Expected block not found; print constructor section manually and patch by hand.

In [49]:
!sed -n '28,50p' /content/CityLens/CityLens/evaluate/global_learned/models.py

        return out
    return out.view(out.size(0), -1)


class TimmEncoder(nn.Module):
    def __init__(self, model_name: str):
        super().__init__()
        self.model_name = model_name
        # Only some timm models (e.g., ViTs) accept img_size in constructor.
        # ResNet and others can fail if img_size is passed.
        if "vit" in model_name or "dinov2" in model_name:
            self.backbone = timm.create_model(model_name, pretrained=True, num_classes=0, img_size=224)
        else:
            self.backbone = timm.create_model(model_name, pretrained=True, num_classes=0)
        self.feature_dim = getattr(self.backbone, "num_features", None) or getattr(self.backbone, "embed_dim", None)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        out = self.backbone(x)
        feat = reduce_backbone_output(out)
        if self.feature_dim is None:
            self.feature_dim = feat.size(-1)
        return feat

In [50]:
import sys, subprocess, shutil
from pathlib import Path

py = sys.executable

for _ in range(3):
    subprocess.call([py, "-m", "pip", "uninstall", "-y", "numpy", "scipy", "scikit-learn", "pandas"])

base = Path("/usr/local/lib/python3.12/dist-packages")
for p in list(base.glob("numpy")) + list(base.glob("numpy-*.dist-info")) + list(base.glob("numpy.libs")):
    print("rm", p)
    shutil.rmtree(p, ignore_errors=True)

subprocess.check_call([
    py, "-m", "pip", "install", "--no-cache-dir", "--no-deps",
    "numpy==1.26.4",
])
subprocess.check_call([
    py, "-m", "pip", "install", "--no-cache-dir",
    "scipy==1.13.1", "scikit-learn==1.5.2", "pandas==2.2.2",
])

0

In [51]:
# Run controls for targeted fusion completion
TASKS_TO_RUN = ['acc2health']   # skip gdp, acc2health now
SAT_MODELS_TO_RUN = ['resnet50_sat']  # ignored since RUN_SATELLITE=False

# Option A (most compact)
STREET_MODELS_TO_RUN = ['resnet50']
FUSION_TYPES_TO_RUN = ['gated']

RUN_SATELLITE = False
RUN_STREET = False
RUN_FUSION = False
if RUN_SATELLITE:
    run_satellite_matrix(TASKS_TO_RUN, SAT_MODELS_TO_RUN)

if RUN_STREET:
    run_street_matrix(TASKS_TO_RUN, STREET_MODELS_TO_RUN)

if RUN_FUSION:
    # Uses Prithvi satellite branch plus each selected street model.
    run_fusion_matrix(
        TASKS_TO_RUN,
        STREET_MODELS_TO_RUN,
        fusion_types=FUSION_TYPES_TO_RUN,
        satellite_model='prithvi_rgb_lora',
    )

if not any([RUN_SATELLITE, RUN_STREET, RUN_FUSION]):
    print('Dry run mode: all run switches are False.')
    print('Set RUN_STREET=True to start the next step.')

Dry run mode: all run switches are False.
Set RUN_STREET=True to start the next step.

In [52]:
!/content/citylens_venv/bin/python -m pip install -U pip
!/content/citylens_venv/bin/python -m pip install --no-cache-dir torch torchvision

Requirement already satisfied: pip in ./citylens_venv/lib/python3.12/site-packages (26.0.1)
Collecting torch
  Downloading torch-2.10.0-3-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (31 kB)
Collecting torchvision
  Downloading torchvision-0.25.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.4 kB)
Collecting filelock (from torch)
  Downloading filelock-3.25.2-py3-none-any.whl.metadata (2.0 kB)
Collecting typing-extensions>=4.10.0 (from torch)
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting setuptools (from torch)
  Downloading setuptools-82.0.1-py3-none-any.whl.metadata (6.5 kB)
Collecting sympy>=1.13.3 (from torch)
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx>=2.5.1 (from torch)
  Downloading networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Collecting jinja2 (from torch)
  Downloading jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting fsspec>=0.8.5 (from torch)
  Downloading fsspec-2026.2.0-py3-none-any.whl.metadata (10 kB)
Collecting cuda-bindings==12.9.4 (from torch)
  Downloading cuda_bindings-12.9.4-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (2.6 kB)
Collecting nvidia-cuda-nvrtc-cu12==12.8.93 (from torch)
  Downloading nvidia_cuda_nvrtc_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-runtime-cu12==12.8.90 (from torch)
  Downloading nvidia_cuda_runtime_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-cupti-cu12==12.8.90 (from torch)
  Downloading nvidia_cuda_cupti_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cudnn-cu12==9.10.2.21 (from torch)
  Downloading nvidia_cudnn_cu12-9.10.2.21-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cublas-cu12==12.8.4.1 (from torch)
  Downloading nvidia_cublas_cu12-12.8.4.1-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufft-cu12==11.3.3.83 (from torch)
  Downloading nvidia_cufft_cu12-11.3.3.83-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-curand-cu12==10.3.9.90 (from torch)
  Downloading nvidia_curand_cu12-10.3.9.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cusolver-cu12==11.7.3.90 (from torch)
  Downloading nvidia_cusolver_cu12-11.7.3.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparse-cu12==12.5.8.93 (from torch)
  Downloading nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparselt-cu12==0.7.1 (from torch)
  Downloading nvidia_cusparselt_cu12-0.7.1-py3-none-manylinux2014_x86_64.whl.metadata (7.0 kB)
Collecting nvidia-nccl-cu12==2.27.5 (from torch)
  Downloading nvidia_nccl_cu12-2.27.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.0 kB)
Collecting nvidia-nvshmem-cu12==3.4.5 (from torch)
  Downloading nvidia_nvshmem_cu12-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.1 kB)
Collecting nvidia-nvtx-cu12==12.8.90 (from torch)
  Downloading nvidia_nvtx_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvjitlink-cu12==12.8.93 (from torch)
  Downloading nvidia_nvjitlink_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufile-cu12==1.13.1.3 (from torch)
  Downloading nvidia_cufile_cu12-1.13.1.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting triton==3.6.0 (from torch)
  Downloading triton-3.6.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.7 kB)
Collecting cuda-pathfinder~=1.1 (from cuda-bindings==12.9.4->torch)
  Downloading cuda_pathfinder-1.4.3-py3-none-any.whl.metadata (1.9 kB)
Requirement already satisfied: numpy in ./citylens_venv/lib/python3.12/site-packages (from torchvision) (1.26.4)
Collecting pillow!=8.3.*,>=5.3.0 (from torchvision)
  Downloading pillow-12.1.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.8 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch)
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch)
  Downloading markupsafe-3.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.7 kB)
Downloading torch-2.10.0-3-cp312-cp312-manylinux_2_28_x86_64.whl (915.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 915.6/915.6 MB 530.8 MB/s  0:00:01
Downloading cuda_bindings-12.9.4-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (12.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 560.9 MB/s  0:00:00
Downloading nvidia_cublas_cu12-12.8.4.1-py3-none-manylinux_2_27_x86_64.whl (594.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 594.3/594.3 MB 520.4 MB/s  0:00:01
Downloading nvidia_cuda_cupti_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (10.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 530.7 MB/s  0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (88.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.0/88.0 MB 606.9 MB/s  0:00:00
Downloading nvidia_cuda_runtime_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (954 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 954.8/954.8 kB 618.8 MB/s  0:00:00
Downloading nvidia_cudnn_cu12-9.10.2.21-py3-none-manylinux_2_27_x86_64.whl (706.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 706.8/706.8 MB 537.1 MB/s  0:00:01
Downloading nvidia_cufft_cu12-11.3.3.83-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (193.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.1/193.1 MB 611.7 MB/s  0:00:00
Downloading nvidia_cufile_cu12-1.13.1.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 673.9 MB/s  0:00:00
Downloading nvidia_curand_cu12-10.3.9.90-py3-none-manylinux_2_27_x86_64.whl (63.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.6/63.6 MB 496.2 MB/s  0:00:00
Downloading nvidia_cusolver_cu12-11.7.3.90-py3-none-manylinux_2_27_x86_64.whl (267.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 267.5/267.5 MB 101.0 MB/s  0:00:02
Downloading nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (288.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 288.2/288.2 MB 506.7 MB/s  0:00:00
Downloading nvidia_cusparselt_cu12-0.7.1-py3-none-manylinux2014_x86_64.whl (287.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 287.2/287.2 MB 557.2 MB/s  0:00:00
Downloading nvidia_nccl_cu12-2.27.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (322.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 322.3/322.3 MB 528.9 MB/s  0:00:00
Downloading nvidia_nvjitlink_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (39.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.3/39.3 MB 523.3 MB/s  0:00:00
Downloading nvidia_nvshmem_cu12-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (139.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.1/139.1 MB 531.3 MB/s  0:00:00
Downloading nvidia_nvtx_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (89 kB)
Downloading triton-3.6.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (188.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.3/188.3 MB 535.7 MB/s  0:00:00
Downloading cuda_pathfinder-1.4.3-py3-none-any.whl (47 kB)
Downloading torchvision-0.25.0-cp312-cp312-manylinux_2_28_x86_64.whl (8.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 429.7 MB/s  0:00:00
Downloading fsspec-2026.2.0-py3-none-any.whl (202 kB)
Downloading networkx-3.6.1-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 671.5 MB/s  0:00:00
Downloading pillow-12.1.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (7.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 616.0 MB/s  0:00:00
Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 689.9 MB/s  0:00:00
Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 618.4 MB/s  0:00:00
Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Downloading filelock-3.25.2-py3-none-any.whl (26 kB)
Downloading jinja2-3.1.6-py3-none-any.whl (134 kB)
Downloading markupsafe-3.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (22 kB)
Downloading setuptools-82.0.1-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 718.6 MB/s  0:00:00
Installing collected packages: nvidia-cusparselt-cu12, mpmath, typing-extensions, triton, sympy, setuptools, pillow, nvidia-nvtx-cu12, nvidia-nvshmem-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufile-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, networkx, MarkupSafe, fsspec, filelock, cuda-pathfinder, nvidia-cusparse-cu12, nvidia-cufft-cu12, nvidia-cudnn-cu12, jinja2, cuda-bindings, nvidia-cusolver-cu12, torch, torchvision
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 30/30 [torchvision]
Successfully installed MarkupSafe-3.0.3 cuda-bindings-12.9.4 cuda-pathfinder-1.4.3 filelock-3.25.2 fsspec-2026.2.0 jinja2-3.1.6 mpmath-1.3.0 networkx-3.6.1 nvidia-cublas-cu12-12.8.4.1 nvidia-cuda-cupti-cu12-12.8.90 nvidia-cuda-nvrtc-cu12-12.8.93 nvidia-cuda-runtime-cu12-12.8.90 nvidia-cudnn-cu12-9.10.2.21 nvidia-cufft-cu12-11.3.3.83 nvidia-cufile-cu12-1.13.1.3 nvidia-curand-cu12-10.3.9.90 nvidia-cusolver-cu12-11.7.3.90 nvidia-cusparse-cu12-12.5.8.93 nvidia-cusparselt-cu12-0.7.1 nvidia-nccl-cu12-2.27.5 nvidia-nvjitlink-cu12-12.8.93 nvidia-nvshmem-cu12-3.4.5 nvidia-nvtx-cu12-12.8.90 pillow-12.1.1 setuptools-82.0.1 sympy-1.14.0 torch-2.10.0 torchvision-0.25.0 triton-3.6.0 typing-extensions-4.15.0

In [53]:
!/content/citylens_venv/bin/python -m pip install --no-cache-dir \
  timm==1.0.9 peft==0.12.0 terratorch safetensors tqdm pillow pyyaml

Collecting timm==1.0.9
  Downloading timm-1.0.9-py3-none-any.whl.metadata (42 kB)
Collecting peft==0.12.0
  Downloading peft-0.12.0-py3-none-any.whl.metadata (13 kB)
Collecting terratorch
  Downloading terratorch-1.2.4-py3-none-any.whl.metadata (13 kB)
Collecting safetensors
  Downloading safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting tqdm
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: pillow in ./citylens_venv/lib/python3.12/site-packages (12.1.1)
Collecting pyyaml
  Downloading pyyaml-6.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.4 kB)
Requirement already satisfied: torch in ./citylens_venv/lib/python3.12/site-packages (from timm==1.0.9) (2.10.0)
Requirement already satisfied: torchvision in ./citylens_venv/lib/python3.12/site-packages (from timm==1.0.9) (0.25.0)
Collecting huggingface_hub (from timm==1.0.9)
  Downloading huggingface_hub-1.7.2-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.17 in ./citylens_venv/lib/python3.12/site-packages (from peft==0.12.0) (1.26.4)
Requirement already satisfied: packaging>=20.0 in ./citylens_venv/lib/python3.12/site-packages (from peft==0.12.0) (26.0)
Collecting psutil (from peft==0.12.0)
  Downloading psutil-7.2.2-cp36-abi3-manylinux2010_x86_64.manylinux_2_12_x86_64.manylinux_2_28_x86_64.whl.metadata (22 kB)
Collecting transformers (from peft==0.12.0)
  Downloading transformers-5.3.0-py3-none-any.whl.metadata (32 kB)
Collecting accelerate>=0.21.0 (from peft==0.12.0)
  Downloading accelerate-1.13.0-py3-none-any.whl.metadata (19 kB)
Collecting numpy>=1.17 (from peft==0.12.0)
  Downloading numpy-2.4.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting rioxarray (from terratorch)
  Downloading rioxarray-0.22.0-py3-none-any.whl.metadata (5.4 kB)
Collecting albumentations (from terratorch)
  Downloading albumentations-2.0.8-py3-none-any.whl.metadata (43 kB)
Collecting albucore (from terratorch)
  Downloading albucore-0.0.41-py3-none-any.whl.metadata (10 kB)
Collecting rasterio (from terratorch)
  Downloading rasterio-1.5.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (8.6 kB)
Collecting torchmetrics (from terratorch)
  Downloading torchmetrics-1.9.0-py3-none-any.whl.metadata (23 kB)
Collecting geopandas (from terratorch)
  Downloading geopandas-1.1.3-py3-none-any.whl.metadata (2.3 kB)
Collecting lightly==1.5.22 (from terratorch)
  Downloading lightly-1.5.22-py3-none-any.whl.metadata (38 kB)
Collecting h5py (from terratorch)
  Downloading h5py-3.16.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Collecting lightning>=2.6.0 (from terratorch)
  Downloading lightning-2.6.1-py3-none-any.whl.metadata (44 kB)
Collecting segmentation-models-pytorch>=0.5.0 (from terratorch)
  Downloading segmentation_models_pytorch-0.5.0-py3-none-any.whl.metadata (17 kB)
Collecting jsonargparse>=4.40.0 (from terratorch)
  Downloading jsonargparse-4.47.0-py3-none-any.whl.metadata (12 kB)
Collecting torchgeo (from terratorch)
  Downloading torchgeo-0.9.0-py3-none-any.whl.metadata (19 kB)
Collecting einops (from terratorch)
  Downloading einops-0.8.2-py3-none-any.whl.metadata (13 kB)
INFO: pip is looking at multiple versions of terratorch to determine which version is compatible with other requirements. This could take a while.
Collecting terratorch
  Downloading terratorch-1.2.2-py3-none-any.whl.metadata (12 kB)
  Downloading terratorch-1.2.1-py3-none-any.whl.metadata (12 kB)
  Downloading terratorch-1.2-py3-none-any.whl.metadata (12 kB)
  Downloading terratorch-1.1.1-py3-none-any.whl.metadata (13 kB)
Collecting albumentations==1.4.10 (from terratorch)
  Downloading albumentations-1.4.10-py3-none-any.whl.metadata (38 kB)
Collecting albucore==0.0.16 (from terratorch)
  Downloading albucore-0.0.16-py3-none-any.whl.metadata (3.1 kB)
Collecting jsonargparse<=4.35.0 (from terratorch)
  Downloading jsonargparse-4.35.0-py3-none-any.whl.metadata (12 kB)
Collecting torchgeo<0.7.2,>=0.7.0 (from terratorch)
  Downloading torchgeo-0.7.1-py3-none-any.whl.metadata (18 kB)
Collecting terratorch
  Downloading terratorch-1.1-py3-none-any.whl.metadata (11 kB)
Collecting hdf5plugin (from terratorch)
  Downloading hdf5plugin-6.0.0-py3-none-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.3 kB)
Collecting numba (from terratorch)
  Downloading numba-0.64.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.9 kB)
Collecting mlflow (from terratorch)
  Downloading mlflow-3.10.1-py3-none-any.whl.metadata (31 kB)
Collecting segmentation-models-pytorch<=0.4 (from terratorch)
  Downloading segmentation_models_pytorch-0.4.0-py3-none-any.whl.metadata (32 kB)
Collecting pytest (from terratorch)
  Downloading pytest-9.0.2-py3-none-any.whl.metadata (7.6 kB)
Collecting terratorch
  Downloading terratorch-1.0.2-py3-none-any.whl.metadata (10 kB)
Collecting torch (from timm==1.0.9)
  Downloading torch-2.7.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (29 kB)
Collecting torchvision (from timm==1.0.9)
  Downloading torchvision-0.22.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (6.1 kB)
Collecting rioxarray==0.19.0 (from terratorch)
  Downloading rioxarray-0.19.0-py3-none-any.whl.metadata (5.5 kB)
Collecting albumentations==1.4.6 (from terratorch)
  Downloading albumentations-1.4.6-py3-none-any.whl.metadata (37 kB)
Collecting rasterio==1.4.3 (from terratorch)
  Downloading rasterio-1.4.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.1 kB)
Collecting torchmetrics==1.7.1 (from terratorch)
  Downloading torchmetrics-1.7.1-py3-none-any.whl.metadata (21 kB)
Collecting geopandas==1.0.1 (from terratorch)
  Downloading geopandas-1.0.1-py3-none-any.whl.metadata (2.2 kB)
Collecting lightly==1.5.20 (from terratorch)
  Downloading lightly-1.5.20-py3-none-any.whl.metadata (37 kB)
Collecting h5py==3.13.0 (from terratorch)
  Downloading h5py-3.13.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
Collecting mlflow==2.22.0 (from terratorch)
  Downloading mlflow-2.22.0-py3-none-any.whl.metadata (30 kB)
Collecting lightning==2.5.1.post0 (from terratorch)
  Downloading lightning-2.5.1.post0-py3-none-any.whl.metadata (39 kB)
Collecting pytest==8.3.5 (from terratorch)
  Downloading pytest-8.3.5-py3-none-any.whl.metadata (7.6 kB)
Collecting torchgeo==0.7.0 (from terratorch)
  Downloading torchgeo-0.7.0-py3-none-any.whl.metadata (19 kB)
Collecting einops==0.8.1 (from terratorch)
  Downloading einops-0.8.1-py3-none-any.whl.metadata (13 kB)
Collecting terratorch
  Downloading terratorch-1.0.1-py3-none-any.whl.metadata (9.1 kB)
Collecting torch (from timm==1.0.9)
  Downloading torch-2.6.0-cp312-cp312-manylinux1_x86_64.whl.metadata (28 kB)
Collecting torchvision (from timm==1.0.9)
  Downloading torchvision-0.21.0-cp312-cp312-manylinux1_x86_64.whl.metadata (6.1 kB)
Collecting lightly==1.5.19 (from terratorch)
  Downloading lightly-1.5.19-py3-none-any.whl.metadata (36 kB)
Collecting mlflow==2.21.3 (from terratorch)
  Downloading mlflow-2.21.3-py3-none-any.whl.metadata (30 kB)
Collecting lightning==2.5.1 (from terratorch)
  Downloading lightning-2.5.1-py3-none-any.whl.metadata (39 kB)
INFO: pip is still looking at multiple versions of terratorch to determine which version is compatible with other requirements. This could take a while.
Collecting terratorch
  Downloading terratorch-1.0-py3-none-any.whl.metadata (8.6 kB)
  Downloading terratorch-0.99.9.post1-py3-none-any.whl.metadata (7.1 kB)
Collecting rioxarray==0.18.2 (from terratorch)
  Downloading rioxarray-0.18.2-py3-none-any.whl.metadata (5.4 kB)
Collecting torchmetrics==1.6.2 (from terratorch)
  Downloading torchmetrics-1.6.2-py3-none-any.whl.metadata (20 kB)
Collecting mlflow==2.20.3 (from terratorch)
  Downloading mlflow-2.20.3-py3-none-any.whl.metadata (30 kB)
Collecting lightning==2.5.0.post0 (from terratorch)
  Downloading lightning-2.5.0.post0-py3-none-any.whl.metadata (40 kB)
Collecting torchgeo==0.6.2 (from terratorch)
  Downloading torchgeo-0.6.2-py3-none-any.whl.metadata (19 kB)
Collecting terratorch
  Downloading terratorch-0.99.9-py3-none-any.whl.metadata (6.4 kB)
  Downloading terratorch-0.99.8-py3-none-any.whl.metadata (6.4 kB)
Collecting torchmetrics==1.6.1 (from terratorch)
  Downloading torchmetrics-1.6.1-py3-none-any.whl.metadata (21 kB)
Collecting lightly==1.5.18 (from terratorch)
  Downloading lightly-1.5.18-py3-none-any.whl.metadata (36 kB)
Collecting h5py==3.12.1 (from terratorch)
  Downloading h5py-3.12.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
Collecting mlflow==2.20.1 (from terratorch)
  Downloading mlflow-2.20.1-py3-none-any.whl.metadata (30 kB)
Collecting pytest==8.3.4 (from terratorch)
  Downloading pytest-8.3.4-py3-none-any.whl.metadata (7.5 kB)
Collecting einops==0.8.0 (from terratorch)
  Downloading einops-0.8.0-py3-none-any.whl.metadata (12 kB)
Collecting opencv-python-headless>=4.9.0.80 (from albucore==0.0.16->terratorch)
  Downloading opencv_python_headless-4.13.0.92-cp37-abi3-manylinux_2_28_x86_64.whl.metadata (19 kB)
Requirement already satisfied: scipy>=1.10.0 in ./citylens_venv/lib/python3.12/site-packages (from albumentations==1.4.10->terratorch) (1.13.1)
Collecting scikit-image>=0.21.0 (from albumentations==1.4.10->terratorch)
  Downloading scikit_image-0.26.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (15 kB)
Requirement already satisfied: typing-extensions>=4.9.0 in ./citylens_venv/lib/python3.12/site-packages (from albumentations==1.4.10->terratorch) (4.15.0)
Requirement already satisfied: scikit-learn>=1.3.2 in ./citylens_venv/lib/python3.12/site-packages (from albumentations==1.4.10->terratorch) (1.5.2)
Collecting pydantic>=2.7.0 (from albumentations==1.4.10->terratorch)
  Downloading pydantic-2.12.5-py3-none-any.whl.metadata (90 kB)
Collecting pyogrio>=0.7.2 (from geopandas==1.0.1->terratorch)
  Downloading pyogrio-0.12.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.9 kB)
Requirement already satisfied: pandas>=1.4.0 in ./citylens_venv/lib/python3.12/site-packages (from geopandas==1.0.1->terratorch) (2.2.2)
Collecting pyproj>=3.3.0 (from geopandas==1.0.1->terratorch)
  Downloading pyproj-3.7.2-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (31 kB)
Collecting shapely>=2.0.0 (from geopandas==1.0.1->terratorch)
  Downloading shapely-2.1.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (6.8 kB)
Collecting certifi>=14.05.14 (from lightly==1.5.18->terratorch)
  Downloading certifi-2026.2.25-py3-none-any.whl.metadata (2.5 kB)
Collecting hydra-core>=1.0.0 (from lightly==1.5.18->terratorch)
  Downloading hydra_core-1.3.2-py3-none-any.whl.metadata (5.5 kB)
Collecting lightly_utils~=0.0.0 (from lightly==1.5.18->terratorch)
  Downloading lightly_utils-0.0.2-py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: python_dateutil>=2.5.3 in ./citylens_venv/lib/python3.12/site-packages (from lightly==1.5.18->terratorch) (2.9.0.post0)
Collecting requests>=2.23.0 (from lightly==1.5.18->terratorch)
  Downloading requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: six>=1.10 in ./citylens_venv/lib/python3.12/site-packages (from lightly==1.5.18->terratorch) (1.17.0)
Collecting pytorch_lightning>=1.0.4 (from lightly==1.5.18->terratorch)
  Downloading pytorch_lightning-2.6.1-py3-none-any.whl.metadata (21 kB)
Collecting urllib3>=1.25.3 (from lightly==1.5.18->terratorch)
  Downloading urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Collecting aenum>=3.1.11 (from lightly==1.5.18->terratorch)
  Downloading aenum-3.1.17-py3-none-any.whl.metadata (3.8 kB)
Collecting fsspec<2026.0,>=2022.5.0 (from fsspec[http]<2026.0,>=2022.5.0->lightning==2.5.0.post0->terratorch)
  Downloading fsspec-2025.12.0-py3-none-any.whl.metadata (10 kB)
Collecting lightning-utilities<2.0,>=0.10.0 (from lightning==2.5.0.post0->terratorch)
  Downloading lightning_utilities-0.15.3-py3-none-any.whl.metadata (5.5 kB)
Collecting packaging>=20.0 (from peft==0.12.0)
  Downloading packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: filelock in ./citylens_venv/lib/python3.12/site-packages (from torch->timm==1.0.9) (3.25.2)
Requirement already satisfied: networkx in ./citylens_venv/lib/python3.12/site-packages (from torch->timm==1.0.9) (3.6.1)
Requirement already satisfied: jinja2 in ./citylens_venv/lib/python3.12/site-packages (from torch->timm==1.0.9) (3.1.6)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch->timm==1.0.9)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch->timm==1.0.9)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch->timm==1.0.9)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch->timm==1.0.9)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch->timm==1.0.9)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch->timm==1.0.9)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch->timm==1.0.9)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch->timm==1.0.9)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch->timm==1.0.9)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparselt-cu12==0.6.2 (from torch->timm==1.0.9)
  Downloading nvidia_cusparselt_cu12-0.6.2-py3-none-manylinux2014_x86_64.whl.metadata (6.8 kB)
Collecting nvidia-nccl-cu12==2.21.5 (from torch->timm==1.0.9)
  Downloading nvidia_nccl_cu12-2.21.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.4.127 (from torch->timm==1.0.9)
  Downloading nvidia_nvtx_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch->timm==1.0.9)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting triton==3.2.0 (from torch->timm==1.0.9)
  Downloading triton-3.2.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.4 kB)
Requirement already satisfied: setuptools in ./citylens_venv/lib/python3.12/site-packages (from torch->timm==1.0.9) (82.0.1)
Collecting sympy==1.13.1 (from torch->timm==1.0.9)
  Downloading sympy-1.13.1-py3-none-any.whl.metadata (12 kB)
Collecting mlflow-skinny==2.20.1 (from mlflow==2.20.1->terratorch)
  Downloading mlflow_skinny-2.20.1-py3-none-any.whl.metadata (31 kB)
Collecting Flask<4 (from mlflow==2.20.1->terratorch)
  Downloading flask-3.1.3-py3-none-any.whl.metadata (3.2 kB)
Collecting alembic!=1.10.0,<2 (from mlflow==2.20.1->terratorch)
  Downloading alembic-1.18.4-py3-none-any.whl.metadata (7.2 kB)
Collecting docker<8,>=4.0.0 (from mlflow==2.20.1->terratorch)
  Downloading docker-7.1.0-py3-none-any.whl.metadata (3.8 kB)
Collecting graphene<4 (from mlflow==2.20.1->terratorch)
  Downloading graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting gunicorn<24 (from mlflow==2.20.1->terratorch)
  Downloading gunicorn-23.0.0-py3-none-any.whl.metadata (4.4 kB)
Collecting markdown<4,>=3.3 (from mlflow==2.20.1->terratorch)
  Downloading markdown-3.10.2-py3-none-any.whl.metadata (5.1 kB)
Collecting matplotlib<4 (from mlflow==2.20.1->terratorch)
  Downloading matplotlib-3.10.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (52 kB)
Collecting pyarrow<19,>=4.0.0 (from mlflow==2.20.1->terratorch)
  Downloading pyarrow-18.1.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.3 kB)
Collecting sqlalchemy<3,>=1.4.0 (from mlflow==2.20.1->terratorch)
  Downloading sqlalchemy-2.0.48-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (9.5 kB)
Collecting cachetools<6,>=5.0.0 (from mlflow-skinny==2.20.1->mlflow==2.20.1->terratorch)
  Downloading cachetools-5.5.2-py3-none-any.whl.metadata (5.4 kB)
Collecting click<9,>=7.0 (from mlflow-skinny==2.20.1->mlflow==2.20.1->terratorch)
  Downloading click-8.3.1-py3-none-any.whl.metadata (2.6 kB)
Collecting cloudpickle<4 (from mlflow-skinny==2.20.1->mlflow==2.20.1->terratorch)
  Downloading cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Collecting databricks-sdk<1,>=0.20.0 (from mlflow-skinny==2.20.1->mlflow==2.20.1->terratorch)
  Downloading databricks_sdk-0.102.0-py3-none-any.whl.metadata (40 kB)
Collecting gitpython<4,>=3.1.9 (from mlflow-skinny==2.20.1->mlflow==2.20.1->terratorch)
  Downloading gitpython-3.1.46-py3-none-any.whl.metadata (13 kB)
Collecting importlib_metadata!=4.7.0,<9,>=3.7.0 (from mlflow-skinny==2.20.1->mlflow==2.20.1->terratorch)
  Downloading importlib_metadata-8.9.0-py3-none-any.whl.metadata (4.5 kB)
Collecting opentelemetry-api<3,>=1.9.0 (from mlflow-skinny==2.20.1->mlflow==2.20.1->terratorch)
  Downloading opentelemetry_api-1.40.0-py3-none-any.whl.metadata (1.5 kB)
Collecting opentelemetry-sdk<3,>=1.9.0 (from mlflow-skinny==2.20.1->mlflow==2.20.1->terratorch)
  Downloading opentelemetry_sdk-1.40.0-py3-none-any.whl.metadata (1.6 kB)
Collecting protobuf<6,>=3.12.0 (from mlflow-skinny==2.20.1->mlflow==2.20.1->terratorch)
  Downloading protobuf-5.29.6-cp38-abi3-manylinux2014_x86_64.whl.metadata (592 bytes)
Collecting sqlparse<1,>=0.4.0 (from mlflow-skinny==2.20.1->mlflow==2.20.1->terratorch)
  Downloading sqlparse-0.5.5-py3-none-any.whl.metadata (4.7 kB)
Collecting iniconfig (from pytest==8.3.4->terratorch)
  Downloading iniconfig-2.3.0-py3-none-any.whl.metadata (2.5 kB)
Collecting pluggy<2,>=1.5 (from pytest==8.3.4->terratorch)
  Downloading pluggy-1.6.0-py3-none-any.whl.metadata (4.8 kB)
Collecting affine (from rasterio==1.4.3->terratorch)
  Downloading affine-2.4.0-py3-none-any.whl.metadata (4.0 kB)
Collecting attrs (from rasterio==1.4.3->terratorch)
  Downloading attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting cligj>=0.5 (from rasterio==1.4.3->terratorch)
  Downloading cligj-0.7.2-py3-none-any.whl.metadata (5.0 kB)
Collecting click-plugins (from rasterio==1.4.3->terratorch)
  Downloading click_plugins-1.1.1.2-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting pyparsing (from rasterio==1.4.3->terratorch)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Collecting xarray>=2024.7.0 (from rioxarray==0.18.2->terratorch)
  Downloading xarray-2026.2.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in ./citylens_venv/lib/python3.12/site-packages (from sympy==1.13.1->torch->timm==1.0.9) (1.3.0)
Collecting fiona>=1.8.21 (from torchgeo==0.6.2->terratorch)
  Downloading fiona-1.10.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (56 kB)
Collecting kornia>=0.7.3 (from torchgeo==0.6.2->terratorch)
  Downloading kornia-0.8.2-py2.py3-none-any.whl.metadata (18 kB)
Collecting rtree>=1 (from torchgeo==0.6.2->terratorch)
  Downloading rtree-1.4.1-py3-none-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (2.1 kB)
Collecting Mako (from alembic!=1.10.0,<2->mlflow==2.20.1->terratorch)
  Downloading mako-1.3.10-py3-none-any.whl.metadata (2.9 kB)
Collecting google-auth~=2.0 (from databricks-sdk<1,>=0.20.0->mlflow-skinny==2.20.1->mlflow==2.20.1->terratorch)
  Downloading google_auth-2.49.1-py3-none-any.whl.metadata (6.2 kB)
Collecting blinker>=1.9.0 (from Flask<4->mlflow==2.20.1->terratorch)

In [55]:
!pip install -q virtualenv
!rm -rf /content/citylens_venv
!virtualenv /content/citylens_venv
!/content/citylens_venv/bin/python -m pip install -U pip
!/content/citylens_venv/bin/python -m pip install --no-cache-dir numpy==1.26.4 scipy==1.13.1 scikit-learn==1.5.2 pandas==2.2.2
!/content/citylens_venv/bin/python -m pip install --no-cache-dir torch torchvision
!/content/citylens_venv/bin/python -m pip install --no-cache-dir timm==1.0.9 peft==0.12.0 terratorch safetensors tqdm pillow matplotlib

created virtual environment CPython3.12.12.final.0-64-x86_64 in 163ms
  creator CPython3Posix(dest=/content/citylens_venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/root/.cache/virtualenv)
    added seed packages: pip==26.0.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
Requirement already satisfied: pip in ./citylens_venv/lib/python3.12/site-packages (26.0.1)
Collecting numpy==1.26.4
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Collecting scipy==1.13.1
  Downloading scipy-1.13.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
Collecting scikit-learn==1.5.2
  Downloading scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Collecting pandas==2.2.2
  Downloading pandas-2.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Collecting joblib>=1.2.0 (from scikit-learn==1.5.2)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn==1.5.2)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting python-dateutil>=2.8.2 (from pandas==2.2.2)
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz>=2020.1 (from pandas==2.2.2)
  Downloading pytz-2026.1.post1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas==2.2.2)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas==2.2.2)
  Downloading six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 546.3 MB/s  0:00:00
Downloading scipy-1.13.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.2/38.2 MB 385.1 MB/s  0:00:00
Downloading scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.9/12.9 MB 319.7 MB/s  0:00:00
Downloading pandas-2.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.7/12.7 MB 378.6 MB/s  0:00:00
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Downloading pytz-2026.1.post1-py2.py3-none-any.whl (510 kB)
Downloading six-1.17.0-py2.py3-none-any.whl (11 kB)
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: pytz, tzdata, threadpoolctl, six, numpy, joblib, scipy, python-dateutil, scikit-learn, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10/10 [pandas]
Successfully installed joblib-1.5.3 numpy-1.26.4 pandas-2.2.2 python-dateutil-2.9.0.post0 pytz-2026.1.post1 scikit-learn-1.5.2 scipy-1.13.1 six-1.17.0 threadpoolctl-3.6.0 tzdata-2025.3
Collecting torch
  Downloading torch-2.10.0-3-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (31 kB)
Collecting torchvision
  Downloading torchvision-0.25.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.4 kB)
Collecting filelock (from torch)
  Downloading filelock-3.25.2-py3-none-any.whl.metadata (2.0 kB)
Collecting typing-extensions>=4.10.0 (from torch)
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting setuptools (from torch)
  Downloading setuptools-82.0.1-py3-none-any.whl.metadata (6.5 kB)
Collecting sympy>=1.13.3 (from torch)
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx>=2.5.1 (from torch)
  Downloading networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Collecting jinja2 (from torch)
  Downloading jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting fsspec>=0.8.5 (from torch)
  Downloading fsspec-2026.2.0-py3-none-any.whl.metadata (10 kB)
Collecting cuda-bindings==12.9.4 (from torch)
  Downloading cuda_bindings-12.9.4-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (2.6 kB)
Collecting nvidia-cuda-nvrtc-cu12==12.8.93 (from torch)
  Downloading nvidia_cuda_nvrtc_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-runtime-cu12==12.8.90 (from torch)
  Downloading nvidia_cuda_runtime_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-cupti-cu12==12.8.90 (from torch)
  Downloading nvidia_cuda_cupti_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cudnn-cu12==9.10.2.21 (from torch)
  Downloading nvidia_cudnn_cu12-9.10.2.21-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cublas-cu12==12.8.4.1 (from torch)
  Downloading nvidia_cublas_cu12-12.8.4.1-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufft-cu12==11.3.3.83 (from torch)
  Downloading nvidia_cufft_cu12-11.3.3.83-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-curand-cu12==10.3.9.90 (from torch)
  Downloading nvidia_curand_cu12-10.3.9.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cusolver-cu12==11.7.3.90 (from torch)
  Downloading nvidia_cusolver_cu12-11.7.3.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparse-cu12==12.5.8.93 (from torch)
  Downloading nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparselt-cu12==0.7.1 (from torch)
  Downloading nvidia_cusparselt_cu12-0.7.1-py3-none-manylinux2014_x86_64.whl.metadata (7.0 kB)
Collecting nvidia-nccl-cu12==2.27.5 (from torch)
  Downloading nvidia_nccl_cu12-2.27.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.0 kB)
Collecting nvidia-nvshmem-cu12==3.4.5 (from torch)
  Downloading nvidia_nvshmem_cu12-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.1 kB)
Collecting nvidia-nvtx-cu12==12.8.90 (from torch)
  Downloading nvidia_nvtx_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvjitlink-cu12==12.8.93 (from torch)
  Downloading nvidia_nvjitlink_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufile-cu12==1.13.1.3 (from torch)
  Downloading nvidia_cufile_cu12-1.13.1.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting triton==3.6.0 (from torch)
  Downloading triton-3.6.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.7 kB)
Collecting cuda-pathfinder~=1.1 (from cuda-bindings==12.9.4->torch)
  Downloading cuda_pathfinder-1.4.3-py3-none-any.whl.metadata (1.9 kB)
Requirement already satisfied: numpy in ./citylens_venv/lib/python3.12/site-packages (from torchvision) (1.26.4)
Collecting pillow!=8.3.*,>=5.3.0 (from torchvision)
  Downloading pillow-12.1.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.8 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch)
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch)
  Downloading markupsafe-3.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.7 kB)
Downloading torch-2.10.0-3-cp312-cp312-manylinux_2_28_x86_64.whl (915.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 915.6/915.6 MB 175.2 MB/s  0:00:05
Downloading cuda_bindings-12.9.4-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (12.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 164.3 MB/s  0:00:00
Downloading nvidia_cublas_cu12-12.8.4.1-py3-none-manylinux_2_27_x86_64.whl (594.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 594.3/594.3 MB 103.4 MB/s  0:00:04
Downloading nvidia_cuda_cupti_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (10.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 160.7 MB/s  0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (88.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.0/88.0 MB 135.7 MB/s  0:00:00
Downloading nvidia_cuda_runtime_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (954 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 954.8/954.8 kB 288.7 MB/s  0:00:00
Downloading nvidia_cudnn_cu12-9.10.2.21-py3-none-manylinux_2_27_x86_64.whl (706.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 706.8/706.8 MB 130.0 MB/s  0:00:04
Downloading nvidia_cufft_cu12-11.3.3.83-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (193.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.1/193.1 MB 112.7 MB/s  0:00:01
Downloading nvidia_cufile_cu12-1.13.1.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 687.5 MB/s  0:00:00
Downloading nvidia_curand_cu12-10.3.9.90-py3-none-manylinux_2_27_x86_64.whl (63.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.6/63.6 MB 135.4 MB/s  0:00:00
Downloading nvidia_cusolver_cu12-11.7.3.90-py3-none-manylinux_2_27_x86_64.whl (267.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 267.5/267.5 MB 162.4 MB/s  0:00:01
Downloading nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (288.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 288.2/288.2 MB 151.7 MB/s  0:00:01
Downloading nvidia_cusparselt_cu12-0.7.1-py3-none-manylinux2014_x86_64.whl (287.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 287.2/287.2 MB 159.3 MB/s  0:00:01
Downloading nvidia_nccl_cu12-2.27.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (322.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 322.3/322.3 MB 138.7 MB/s  0:00:02
Downloading nvidia_nvjitlink_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (39.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.3/39.3 MB 146.6 MB/s  0:00:00
Downloading nvidia_nvshmem_cu12-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (139.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.1/139.1 MB 161.1 MB/s  0:00:00
Downloading nvidia_nvtx_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (89 kB)
Downloading triton-3.6.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (188.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.3/188.3 MB 176.1 MB/s  0:00:01
Downloading cuda_pathfinder-1.4.3-py3-none-any.whl (47 kB)
Downloading torchvision-0.25.0-cp312-cp312-manylinux_2_28_x86_64.whl (8.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 297.6 MB/s  0:00:00
Downloading fsspec-2026.2.0-py3-none-any.whl (202 kB)
Downloading networkx-3.6.1-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 328.6 MB/s  0:00:00
Downloading pillow-12.1.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (7.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 231.5 MB/s  0:00:00
Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 278.6 MB/s  0:00:00
Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 622.4 MB/s  0:00:00
Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Downloading filelock-3.25.2-py3-none-any.whl (26 kB)
Downloading jinja2-3.1.6-py3-none-any.whl (134 kB)
Downloading markupsafe-3.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (22 kB)
Downloading setuptools-82.0.1-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 703.0 MB/s  0:00:00
Installing collected packages: nvidia-cusparselt-cu12, mpmath, typing-extensions, triton, sympy, setuptools, pillow, nvidia-nvtx-cu12, nvidia-nvshmem-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufile-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, networkx, MarkupSafe, fsspec, filelock, cuda-pathfinder, nvidia-cusparse-cu12, nvidia-cufft-cu12, nvidia-cudnn-cu12, jinja2, cuda-bindings, nvidia-cusolver-cu12, torch, torchvision
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 30/30 [torchvision]
Successfully installed MarkupSafe-3.0.3 cuda-bindings-12.9.4 cuda-pathfinder-1.4.3 filelock-3.25.2 fsspec-2026.2.0 jinja2-3.1.6 mpmath-1.3.0 networkx-3.6.1 nvidia-cublas-cu12-12.8.4.1 nvidia-cuda-cupti-cu12-12.8.90 nvidia-cuda-nvrtc-cu12-12.8.93 nvidia-cuda-runtime-cu12-12.8.90 nvidia-cudnn-cu12-9.10.2.21 nvidia-cufft-cu12-11.3.3.83 nvidia-cufile-cu12-1.13.1.3 nvidia-curand-cu12-10.3.9.90 nvidia-cusolver-cu12-11.7.3.90 nvidia-cusparse-cu12-12.5.8.93 nvidia-cusparselt-cu12-0.7.1 nvidia-nccl-cu12-2.27.5 nvidia-nvjitlink-cu12-12.8.93 nvidia-nvshmem-cu12-3.4.5 nvidia-nvtx-cu12-12.8.90 pillow-12.1.1 setuptools-82.0.1 sympy-1.14.0 torch-2.10.0 torchvision-0.25.0 triton-3.6.0 typing-extensions-4.15.0
Collecting timm==1.0.9
  Downloading timm-1.0.9-py3-none-any.whl.metadata (42 kB)
Collecting peft==0.12.0
  Downloading peft-0.12.0-py3-none-any.whl.metadata (13 kB)
Collecting terratorch
  Downloading terratorch-1.2.4-py3-none-any.whl.metadata (13 kB)
Collecting safetensors
  Downloading safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting tqdm
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: pillow in ./citylens_venv/lib/python3.12/site-packages (12.1.1)
Collecting matplotlib
  Downloading matplotlib-3.10.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (52 kB)
Requirement already satisfied: torch in ./citylens_venv/lib/python3.12/site-packages (from timm==1.0.9) (2.10.0)
Requirement already satisfied: torchvision in ./citylens_venv/lib/python3.12/site-packages (from timm==1.0.9) (0.25.0)
Collecting pyyaml (from timm==1.0.9)
  Downloading pyyaml-6.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.4 kB)
Collecting huggingface_hub (from timm==1.0.9)
  Downloading huggingface_hub-1.7.2-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.17 in ./citylens_venv/lib/python3.12/site-packages (from peft==0.12.0) (1.26.4)
Collecting packaging>=20.0 (from peft==0.12.0)
  Downloading packaging-26.0-py3-none-any.whl.metadata (3.3 kB)
Collecting psutil (from peft==0.12.0)
  Downloading psutil-7.2.2-cp36-abi3-manylinux2010_x86_64.manylinux_2_12_x86_64.manylinux_2_28_x86_64.whl.metadata (22 kB)
Collecting transformers (from peft==0.12.0)
  Downloading transformers-5.3.0-py3-none-any.whl.metadata (32 kB)
Collecting accelerate>=0.21.0 (from peft==0.12.0)
  Downloading accelerate-1.13.0-py3-none-any.whl.metadata (19 kB)
Collecting numpy>=1.17 (from peft==0.12.0)
  Downloading numpy-2.4.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting rioxarray (from terratorch)
  Downloading rioxarray-0.22.0-py3-none-any.whl.metadata (5.4 kB)
Collecting albumentations (from terratorch)
  Downloading albumentations-2.0.8-py3-none-any.whl.metadata (43 kB)
Collecting albucore (from terratorch)
  Downloading albucore-0.0.41-py3-none-any.whl.metadata (10 kB)
Collecting rasterio (from terratorch)
  Downloading rasterio-1.5.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (8.6 kB)
Collecting torchmetrics (from terratorch)
  Downloading torchmetrics-1.9.0-py3-none-any.whl.metadata (23 kB)
Collecting geopandas (from terratorch)
  Downloading geopandas-1.1.3-py3-none-any.whl.metadata (2.3 kB)
Collecting lightly==1.5.22 (from terratorch)
  Downloading lightly-1.5.22-py3-none-any.whl.metadata (38 kB)
Collecting h5py (from terratorch)
  Downloading h5py-3.16.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Collecting lightning>=2.6.0 (from terratorch)
  Downloading lightning-2.6.1-py3-none-any.whl.metadata (44 kB)
Collecting segmentation-models-pytorch>=0.5.0 (from terratorch)
  Downloading segmentation_models_pytorch-0.5.0-py3-none-any.whl.metadata (17 kB)
Collecting jsonargparse>=4.40.0 (from terratorch)
  Downloading jsonargparse-4.47.0-py3-none-any.whl.metadata (12 kB)
Collecting torchgeo (from terratorch)
  Downloading torchgeo-0.9.0-py3-none-any.whl.metadata (19 kB)
Collecting einops (from terratorch)
  Downloading einops-0.8.2-py3-none-any.whl.metadata (13 kB)
INFO: pip is looking at multiple versions of terratorch to determine which version is compatible with other requirements. This could take a while.
Collecting terratorch
  Downloading terratorch-1.2.2-py3-none-any.whl.metadata (12 kB)
  Downloading terratorch-1.2.1-py3-none-any.whl.metadata (12 kB)
  Downloading terratorch-1.2-py3-none-any.whl.metadata (12 kB)
  Downloading terratorch-1.1.1-py3-none-any.whl.metadata (13 kB)
Collecting albumentations==1.4.10 (from terratorch)
  Downloading albumentations-1.4.10-py3-none-any.whl.metadata (38 kB)
Collecting albucore==0.0.16 (from terratorch)
  Downloading albucore-0.0.16-py3-none-any.whl.metadata (3.1 kB)
Collecting jsonargparse<=4.35.0 (from terratorch)
  Downloading jsonargparse-4.35.0-py3-none-any.whl.metadata (12 kB)
Collecting torchgeo<0.7.2,>=0.7.0 (from terratorch)
  Downloading torchgeo-0.7.1-py3-none-any.whl.metadata (18 kB)
Collecting terratorch
  Downloading terratorch-1.1-py3-none-any.whl.metadata (11 kB)
Collecting hdf5plugin (from terratorch)
  Downloading hdf5plugin-6.0.0-py3-none-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.3 kB)
Collecting numba (from terratorch)
  Downloading numba-0.64.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.9 kB)
Collecting mlflow (from terratorch)
  Downloading mlflow-3.10.1-py3-none-any.whl.metadata (31 kB)
Collecting segmentation-models-pytorch<=0.4 (from terratorch)
  Downloading segmentation_models_pytorch-0.4.0-py3-none-any.whl.metadata (32 kB)
Collecting pytest (from terratorch)
  Downloading pytest-9.0.2-py3-none-any.whl.metadata (7.6 kB)
Collecting terratorch
  Downloading terratorch-1.0.2-py3-none-any.whl.metadata (10 kB)
Collecting torch (from timm==1.0.9)
  Downloading torch-2.7.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (29 kB)
Collecting torchvision (from timm==1.0.9)
  Downloading torchvision-0.22.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (6.1 kB)
Collecting rioxarray==0.19.0 (from terratorch)
  Downloading rioxarray-0.19.0-py3-none-any.whl.metadata (5.5 kB)
Collecting albumentations==1.4.6 (from terratorch)
  Downloading albumentations-1.4.6-py3-none-any.whl.metadata (37 kB)
Collecting rasterio==1.4.3 (from terratorch)
  Downloading rasterio-1.4.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.1 kB)
Collecting torchmetrics==1.7.1 (from terratorch)
  Downloading torchmetrics-1.7.1-py3-none-any.whl.metadata (21 kB)
Collecting geopandas==1.0.1 (from terratorch)
  Downloading geopandas-1.0.1-py3-none-any.whl.metadata (2.2 kB)
Collecting lightly==1.5.20 (from terratorch)
  Downloading lightly-1.5.20-py3-none-any.whl.metadata (37 kB)
Collecting h5py==3.13.0 (from terratorch)
  Downloading h5py-3.13.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
Collecting mlflow==2.22.0 (from terratorch)
  Downloading mlflow-2.22.0-py3-none-any.whl.metadata (30 kB)
Collecting lightning==2.5.1.post0 (from terratorch)
  Downloading lightning-2.5.1.post0-py3-none-any.whl.metadata (39 kB)
Collecting pytest==8.3.5 (from terratorch)
  Downloading pytest-8.3.5-py3-none-any.whl.metadata (7.6 kB)
Collecting torchgeo==0.7.0 (from terratorch)
  Downloading torchgeo-0.7.0-py3-none-any.whl.metadata (19 kB)
Collecting einops==0.8.1 (from terratorch)
  Downloading einops-0.8.1-py3-none-any.whl.metadata (13 kB)
Collecting terratorch

In [56]:
!/content/citylens_venv/bin/python -c "import numpy as np; import numpy.rec; import sklearn; print('ok', np.__version__)"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy.rec'

In [57]:
%pip uninstall -y numpy scipy scikit-learn pandas
%pip install --no-cache-dir --force-reinstall --ignore-installed numpy==1.26.4 scipy==1.13.1 scikit-learn==1.5.2 pandas==2.2.2

Found existing installation: numpy 1.26.4
Uninstalling numpy-1.26.4:
  Successfully uninstalled numpy-1.26.4
Found existing installation: scipy 1.13.1
Uninstalling scipy-1.13.1:
  Successfully uninstalled scipy-1.13.1
Found existing installation: scikit-learn 1.5.2
Uninstalling scikit-learn-1.5.2:
  Successfully uninstalled scikit-learn-1.5.2
Found existing installation: pandas 2.2.2
Uninstalling pandas-2.2.2:
  Successfully uninstalled pandas-2.2.2
Collecting numpy==1.26.4
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 134.2 MB/s eta 0:00:00
Collecting scipy==1.13.1
  Downloading scipy-1.13.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 292.2 MB/s eta 0:00:00
Collecting scikit-learn==1.5.2
  Downloading scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Collecting pandas==2.2.2
  Downloading pandas-2.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Collecting joblib>=1.2.0 (from scikit-learn==1.5.2)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn==1.5.2)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting python-dateutil>=2.8.2 (from pandas==2.2.2)
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz>=2020.1 (from pandas==2.2.2)
  Downloading pytz-2026.1.post1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas==2.2.2)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas==2.2.2)
  Downloading six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 221.9 MB/s eta 0:00:00
Downloading scipy-1.13.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.2/38.2 MB 304.0 MB/s eta 0:00:00
Downloading scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.9/12.9 MB 192.1 MB/s eta 0:00:00
Downloading pandas-2.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.7/12.7 MB 87.8 MB/s eta 0:00:00
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 309.1/309.1 kB 368.5 MB/s eta 0:00:00
Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 kB 350.7 MB/s eta 0:00:00
Downloading pytz-2026.1.post1-py2.py3-none-any.whl (510 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.5/510.5 kB 389.2 MB/s eta 0:00:00
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 348.5/348.5 kB 366.2 MB/s eta 0:00:00
Downloading six-1.17.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: pytz, tzdata, threadpoolctl, six, numpy, joblib, scipy, python-dateutil, scikit-learn, pandas
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
shap 0.51.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
cupy-cuda12x 14.0.1 requires numpy<2.6,>=2.0, but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
hdbscan 0.8.41 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
tsfresh 0.21.1 requires scipy>=1.14.0; python_version >= "3.10", but you have scipy 1.13.1 which is incompatible.
access 1.1.10.post3 requires scipy>=1.14.1, but you have scipy 1.13.1 which is incompatible.
umap-learn 0.5.11 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
tobler 0.13.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
Successfully installed joblib-1.5.3 numpy-1.26.4 pandas-2.2.2 python-dateutil-2.9.0.post0 pytz-2026.1.post1 scikit-learn-1.5.2 scipy-1.13.1 six-1.17.0 threadpoolctl-3.6.0 tzdata-2025.3

In [1]:
from pathlib import Path
import json
import pandas as pd

DATA_ROOT = Path('/content/drive/MyDrive/GeoBench/CityLens-Data/CityLens-data')
RESULTS_ROOT = DATA_ROOT / 'Results' / 'global_learned'
TASKS = ['gdp', 'acc2health', 'build_height', 'pop']

def read_json(p):
    try:
        return json.loads(p.read_text())
    except Exception:
        return None

rows = []
for task in TASKS:
    task_dir = RESULTS_ROOT / task
    if not task_dir.exists():
        continue

    for exp_dir in task_dir.iterdir():
        if not exp_dir.is_dir():
            continue
        name = exp_dir.name
        if f"-{task}-" not in f"-{name}-":
            pass
        # focus on fusion runs
        if "-fusion-" not in name:
            continue

        cfg = read_json(exp_dir / "config.json") or {}
        metrics = read_json(exp_dir / "metrics.json")
        history_path = exp_dir / "history.csv"
        best_ckpt = exp_dir / "checkpoints" / "best.pt"
        last_ckpt = exp_dir / "checkpoints" / "last.pt"

        status = "not_started"
        if metrics and best_ckpt.exists():
            status = "finished_or_best_saved"
        elif last_ckpt.exists():
            status = "in_progress_or_interrupted"

        rows.append({
            "task": task,
            "exp_dir": name,
            "street_model": cfg.get("street_model"),
            "fusion_type": cfg.get("fusion_type"),
            "epochs_target": cfg.get("epochs"),
            "best_epoch": (metrics or {}).get("best_epoch"),
            "r2": (metrics or {}).get("r2"),
            "rmse": (metrics or {}).get("rmse"),
            "has_best_pt": best_ckpt.exists(),
            "has_last_pt": last_ckpt.exists(),
            "has_history": history_path.exists(),
            "status": status,
        })

df = pd.DataFrame(rows)
if df.empty:
    print("No fusion runs found yet.")
else:
    display(df.sort_values(["task","street_model","fusion_type"]).reset_index(drop=True))
    print("\nSummary by status:")
    display(df.groupby("status").size().rename("count").reset_index())

,task,exp_dir,street_model,fusion_type,epochs_target,best_epoch,r2,rmse,has_best_pt,has_last_pt,has_history,status
0,acc2health,acc2health-fusion-prithvi_rgb_lora-clip_vitb16...,clip_vitb16,gated,30.0,19.0,0.167151,9.988541e+00,False,False,True,not_started
1,acc2health,acc2health-fusion-prithvi_rgb_lora-clip_vitb16...,clip_vitb16,late,30.0,13.0,0.134735,1.018108e+01,False,False,True,not_started
2,acc2health,acc2health-fusion-prithvi_rgb_lora-resnet50-ga...,resnet50,gated,30.0,3.0,0.161168,1.002436e+01,False,True,True,in_progress_or_interrupted
3,acc2health,acc2health-fusion-prithvi_rgb_lora-resnet50-la...,resnet50,late,30.0,12.0,0.190886,9.845183e+00,False,False,True,not_started
4,acc2health,acc2health-fusion-prithvi_rgb_lora-dinov2_vitb...,None,None,NaN,NaN,NaN,NaN,False,False,False,not_started
5,build_height,build_height-fusion-prithvi_rgb_lora-dinov2_vi...,dinov2_vitb14,gated,30.0,21.0,0.865288,2.596345e+00,False,False,True,not_started
6,build_height,build_height-fusion-prithvi_rgb_lora-dinov2_vi...,dinov2_vitb14,late,30.0,23.0,0.872343,2.527444e+00,False,False,True,not_started
7,build_height,build_height-fusion-prithvi_rgb_lora-resnet50-...,resnet50,gated,30.0,28.0,0.859323,2.653199e+00,False,False,True,not_started
8,build_height,build_height-fusion-prithvi_rgb_lora-resnet50-...,resnet50,late,30.0,28.0,0.848417,2.754131e+00,False,False,True,not_started
9,gdp,gdp-fusion-prithvi_rgb_lora-clip_vitb16-gated-...,clip_vitb16,gated,20.0,18.0,0.015131,5.629208e+08,False,False,True,not_started
10,gdp,gdp-fusion-prithvi_rgb_lora-clip_vitb16-late-m...,clip_vitb16,late,20.0,18.0,0.344951,4.590870e+08,False,False,True,not_started
11,gdp,gdp-fusion-prithvi_rgb_lora-dinov2_vitb14-gate...,dinov2_vitb14,gated,20.0,2.0,0.017164,5.623394e+08,False,True,True,in_progress_or_interrupted
12,gdp,gdp-fusion-prithvi_rgb_lora-dinov2_vitb14-late...,dinov2_vitb14,late,20.0,20.0,0.396610,4.406128e+08,False,False,True,not_started
13,gdp,gdp-fusion-prithvi_rgb_lora-resnet50-gated-mea...,resnet50,gated,20.0,20.0,0.443721,4.230626e+08,False,False,True,not_started
14,gdp,gdp-fusion-prithvi_rgb_lora-resnet50-late-mean...,resnet50,late,20.0,6.0,0.371324,4.497504e+08,False,True,True,in_progress_or_interrupted
15,pop,pop-fusion-prithvi_rgb_lora-dinov2_vitb14-gate...,dinov2_vitb14,gated,5.0,1.0,-0.329123,1.426917e+04,False,False,True,not_started
16,pop,pop-fusion-prithvi_rgb_lora-dinov2_vitb14-late...,dinov2_vitb14,late,5.0,5.0,-0.484851,1.508195e+04,False,False,True,not_started
17,pop,pop-fusion-prithvi_rgb_lora-resnet50-gated-mea...,resnet50,gated,5.0,4.0,-0.294189,1.408040e+04,False,False,True,not_started
18,pop,pop-fusion-prithvi_rgb_lora-resnet50-late-mean...,resnet50,late,5.0,4.0,-0.348694,1.437384e+04,False,False,True,not_started

Summary by status:

                       status  count
0  in_progress_or_interrupted      3
1                 not_started     16

In [2]:
TASKS = ['gdp', 'acc2health', 'build_height', 'pop']
STREET_MODELS = ['clip_vitb16', 'resnet50', 'dinov2_vitb14']
FUSION_TYPES = ['late', 'gated']

done = set()
for _, r in df.iterrows():
    if r["has_best_pt"] and pd.notna(r["r2"]):
        done.add((r["task"], r["street_model"], r["fusion_type"]))

todo = []
for t in TASKS:
    for s in STREET_MODELS:
        for f in FUSION_TYPES:
            if (t, s, f) not in done:
                todo.append((t, s, f))

print(f"Done: {len(done)} | Missing: {len(todo)}")
for x in todo[:50]:
    print("MISSING:", x)

Done: 0 | Missing: 24
MISSING: ('gdp', 'clip_vitb16', 'late')
MISSING: ('gdp', 'clip_vitb16', 'gated')
MISSING: ('gdp', 'resnet50', 'late')
MISSING: ('gdp', 'resnet50', 'gated')
MISSING: ('gdp', 'dinov2_vitb14', 'late')
MISSING: ('gdp', 'dinov2_vitb14', 'gated')
MISSING: ('acc2health', 'clip_vitb16', 'late')
MISSING: ('acc2health', 'clip_vitb16', 'gated')
MISSING: ('acc2health', 'resnet50', 'late')
MISSING: ('acc2health', 'resnet50', 'gated')
MISSING: ('acc2health', 'dinov2_vitb14', 'late')
MISSING: ('acc2health', 'dinov2_vitb14', 'gated')
MISSING: ('build_height', 'clip_vitb16', 'late')
MISSING: ('build_height', 'clip_vitb16', 'gated')
MISSING: ('build_height', 'resnet50', 'late')
MISSING: ('build_height', 'resnet50', 'gated')
MISSING: ('build_height', 'dinov2_vitb14', 'late')
MISSING: ('build_height', 'dinov2_vitb14', 'gated')
MISSING: ('pop', 'clip_vitb16', 'late')
MISSING: ('pop', 'clip_vitb16', 'gated')
MISSING: ('pop', 'resnet50', 'late')
MISSING: ('pop', 'resnet50', 'gated')
MISSING: ('pop', 'dinov2_vitb14', 'late')
MISSING: ('pop', 'dinov2_vitb14', 'gated')

In [3]:
def find_metrics(task_name: str, satellite_model: str, epochs: int):
    task_root = RESULTS_ROOT / task_name
    if not task_root.exists():
        return None
    pattern = f"{task_name}-satellite-{satellite_model}-clip_vitb16-bs8-ep{epochs}-lr0.0002-blr0.0002-hlr0.001-ttlog1p-seed42"
    exp_dir = task_root / pattern
    metrics_path = exp_dir / 'metrics.json'
    if not metrics_path.exists():
        return None
    payload = json.loads(metrics_path.read_text())
    return {
        'task': task_name,
        'model': satellite_model,
        'epochs': epochs,
        'best_epoch': payload.get('best_epoch'),
        'r2': payload.get('r2'),
        'rmse': payload.get('rmse'),
        'mae': payload.get('mae'),
        'mse': payload.get('mse'),
        'path': str(exp_dir),
    }


rows = []
for task_name, ref in LOCKED_PRITHVI.items():
    rows.append({
        'task': task_name,
        'model': 'prithvi_rgb_lora',
        'epochs': ref['epochs'],
        'best_epoch': ref['best_epoch'],
        'r2': ref['r2'],
        'rmse': ref['rmse'],
        'mae': None,
        'mse': None,
        'path': 'docs/PRITHVI_SATELLITE_REFERENCE.md',
    })

for task_name in TASK_EPOCHS:
    for satellite_model in ['dinov2_sat', 'resnet50_sat']:
        row = find_metrics(task_name, satellite_model, TASK_EPOCHS[task_name])
        if row is not None:
            rows.append(row)

df = pd.DataFrame(rows)
df.sort_values(['task', 'model']) if not df.empty else df

NameError: name 'LOCKED_PRITHVI' is not defined

In [9]:
if df.empty:
    print('No baseline comparison rows found yet.')
else:
    pivot = df.pivot_table(index='task', columns='model', values='r2', aggfunc='first')
    display(pivot)

    wins = 0
    considered = 0
    for task_name in ['build_height', 'gdp', 'acc2health']:
        if task_name not in pivot.index:
            continue
        if 'prithvi_rgb_lora' not in pivot.columns:
            continue
        other_values = [pivot.loc[task_name, c] for c in pivot.columns if c != 'prithvi_rgb_lora' and pd.notna(pivot.loc[task_name, c])]
        if not other_values:
            continue
        considered += 1
        if pivot.loc[task_name, 'prithvi_rgb_lora'] > max(other_values):
            wins += 1

    if considered == 0:
        print('Need baseline runs before making the modality decision.')
    elif wins >= 2:
        print('Recommendation: proceed to street-only clip_vitb16 and late fusion next.')
    else:
        print('Recommendation: stop and frame this as a smaller satellite empirical study unless stronger baseline results arrive.')

KeyError: 'model'

In [5]:
from pathlib import Path
import json
import pandas as pd

root = Path("/content/drive/MyDrive/GeoBench/CityLens-Data/CityLens-data/Results/global_learned")

tasks = ["gdp", "acc2health", "build_height", "pop"]
models = ["prithvi_rgb_lora", "dinov2_sat", "resnet50_sat"]

# Epoch budgets you used
task_epochs = {"gdp": 20, "acc2health": 30, "build_height": 30, "pop": 5}

rows = []
for t in tasks:
    for m in models:
        exp = root / t / f"{t}-satellite-{m}-clip_vitb16-bs8-ep{task_epochs[t]}-lr0.0002-blr0.0002-hlr0.001-ttlog1p-seed42"
        mp = exp / "metrics.json"
        if mp.exists():
            d = json.loads(mp.read_text())
            rows.append({
                "task": t, "model": m,
                "best_epoch": d.get("best_epoch"),
                "r2": d.get("r2"),
                "rmse": d.get("rmse"),
                "mae": d.get("mae"),
                "path": str(exp)
            })
        else:
            rows.append({
                "task": t, "model": m,
                "best_epoch": None, "r2": None, "rmse": None, "mae": None,
                "path": f"MISSING: {exp}"
            })

df = pd.DataFrame(rows)
print(df.sort_values(["task","model"]).to_string(index=False))

print("\nR2 Pivot:")
print(df.pivot_table(index="task", columns="model", values="r2", aggfunc="first"))

        task            model  best_epoch        r2         rmse          mae                                                                                                                                                                                                    path
  acc2health       dinov2_sat          20  0.098492 1.161133e+01 8.774560e+00           /content/drive/MyDrive/GeoBench/CityLens-Data/CityLens-data/Results/global_learned/acc2health/acc2health-satellite-dinov2_sat-clip_vitb16-bs8-ep30-lr0.0002-blr0.0002-hlr0.001-ttlog1p-seed42
  acc2health prithvi_rgb_lora           9  0.390141 9.550184e+00 7.191029e+00     /content/drive/MyDrive/GeoBench/CityLens-Data/CityLens-data/Results/global_learned/acc2health/acc2health-satellite-prithvi_rgb_lora-clip_vitb16-bs8-ep30-lr0.0002-blr0.0002-hlr0.001-ttlog1p-seed42
  acc2health     resnet50_sat          22  0.212407 1.085295e+01 7.204183e+00         /content/drive/MyDrive/GeoBench/CityLens-Data/CityLens-data/Results/global_learned/acc2health/acc2health-satellite-resnet50_sat-clip_vitb16-bs8-ep30-lr0.0002-blr0.0002-hlr0.001-ttlog1p-seed42
build_height       dinov2_sat          18  0.679090 3.954163e+00 2.812445e+00       /content/drive/MyDrive/GeoBench/CityLens-Data/CityLens-data/Results/global_learned/build_height/build_height-satellite-dinov2_sat-clip_vitb16-bs8-ep30-lr0.0002-blr0.0002-hlr0.001-ttlog1p-seed42
build_height prithvi_rgb_lora          11  0.859866 2.612972e+00 1.909996e+00 /content/drive/MyDrive/GeoBench/CityLens-Data/CityLens-data/Results/global_learned/build_height/build_height-satellite-prithvi_rgb_lora-clip_vitb16-bs8-ep30-lr0.0002-blr0.0002-hlr0.001-ttlog1p-seed42
build_height     resnet50_sat          26  0.800435 3.118209e+00 2.280582e+00     /content/drive/MyDrive/GeoBench/CityLens-Data/CityLens-data/Results/global_learned/build_height/build_height-satellite-resnet50_sat-clip_vitb16-bs8-ep30-lr0.0002-blr0.0002-hlr0.001-ttlog1p-seed42
         gdp       dinov2_sat          19  0.453492 3.784510e+08 2.328081e+08                         /content/drive/MyDrive/GeoBench/CityLens-Data/CityLens-data/Results/global_learned/gdp/gdp-satellite-dinov2_sat-clip_vitb16-bs8-ep20-lr0.0002-blr0.0002-hlr0.001-ttlog1p-seed42
         gdp prithvi_rgb_lora          14  0.580773 3.314636e+08 1.981141e+08                   /content/drive/MyDrive/GeoBench/CityLens-Data/CityLens-data/Results/global_learned/gdp/gdp-satellite-prithvi_rgb_lora-clip_vitb16-bs8-ep20-lr0.0002-blr0.0002-hlr0.001-ttlog1p-seed42
         gdp     resnet50_sat           5 -4.004642 1.145243e+09 3.933633e+08                       /content/drive/MyDrive/GeoBench/CityLens-Data/CityLens-data/Results/global_learned/gdp/gdp-satellite-resnet50_sat-clip_vitb16-bs8-ep20-lr0.0002-blr0.0002-hlr0.001-ttlog1p-seed42
         pop       dinov2_sat           5 -0.183969 2.317554e+04 1.136306e+04                          /content/drive/MyDrive/GeoBench/CityLens-Data/CityLens-data/Results/global_learned/pop/pop-satellite-dinov2_sat-clip_vitb16-bs8-ep5-lr0.0002-blr0.0002-hlr0.001-ttlog1p-seed42
         pop prithvi_rgb_lora           2 -0.032393 2.164125e+04 1.002026e+04                    /content/drive/MyDrive/GeoBench/CityLens-Data/CityLens-data/Results/global_learned/pop/pop-satellite-prithvi_rgb_lora-clip_vitb16-bs8-ep5-lr0.0002-blr0.0002-hlr0.001-ttlog1p-seed42
         pop     resnet50_sat           2 -0.266080 2.396572e+04 1.187183e+04                        /content/drive/MyDrive/GeoBench/CityLens-Data/CityLens-data/Results/global_learned/pop/pop-satellite-resnet50_sat-clip_vitb16-bs8-ep5-lr0.0002-blr0.0002-hlr0.001-ttlog1p-seed42

R2 Pivot:
model         dinov2_sat  prithvi_rgb_lora  resnet50_sat
task
acc2health      0.098492          0.390141      0.212407
build_height    0.679090          0.859866      0.800435
gdp             0.453492          0.580773     -4.004642
pop            -0.183969         -0.032393     -0.266080

## Next-phase result summary (street + fusion)

Use this after running any of:

- street-only matrix
- fusion matrix

It scans `Results/global_learned/<task>/` and summarizes the best available runs for each branch/model combination under the same hyperparameter naming convention.

In [6]:
from pathlib import Path
import json
import pandas as pd

RESULTS_ROOT = DATA_ROOT / 'Results' / 'global_learned'
TASKS = ['gdp', 'acc2health', 'build_height', 'pop']


def load_metrics(exp_dir: Path):
    mp = exp_dir / 'metrics.json'
    if not mp.exists():
        return None
    payload = json.loads(mp.read_text())
    return {
        'best_epoch': payload.get('best_epoch'),
        'r2': payload.get('r2'),
        'rmse': payload.get('rmse'),
        'mae': payload.get('mae'),
        'mse': payload.get('mse'),
    }


def collect_branch_rows(task_name: str, branch: str):
    task_root = RESULTS_ROOT / task_name
    if not task_root.exists():
        return []
    rows = []
    for exp_dir in sorted([p for p in task_root.iterdir() if p.is_dir()]):
        name = exp_dir.name
        if f"{task_name}-{branch}-" not in name:
            continue
        metrics = load_metrics(exp_dir)
        if metrics is None:
            continue
        rows.append({
            'task': task_name,
            'branch': branch,
            'experiment': name,
            **metrics,
            'path': str(exp_dir),
        })
    return rows


all_rows = []
for t in TASKS:
    all_rows.extend(collect_branch_rows(t, 'satellite'))
    all_rows.extend(collect_branch_rows(t, 'street'))
    all_rows.extend(collect_branch_rows(t, 'fusion'))

summary_df = pd.DataFrame(all_rows)

if summary_df.empty:
    print('No metrics found yet for satellite/street/fusion in selected tasks.')
else:
    display(summary_df.sort_values(['task', 'branch', 'r2'], ascending=[True, True, False]).head(200))

    best_per_task_branch = (
        summary_df
        .sort_values(['task', 'branch', 'r2'], ascending=[True, True, False])
        .groupby(['task', 'branch'], as_index=False)
        .first()
    )

    print('\nBest run per task and branch:')
    display(best_per_task_branch[['task', 'branch', 'experiment', 'best_epoch', 'r2', 'rmse', 'mae']])

    print('\nR2 pivot (best per task/branch):')
    display(best_per_task_branch.pivot(index='task', columns='branch', values='r2'))

,task,branch,experiment,best_epoch,r2,rmse,mae,mse,path
24,acc2health,fusion,acc2health-fusion-prithvi_rgb_lora-resnet50-la...,12,0.190886,9.845183e+00,7.096077e+00,9.692764e+01,/content/drive/MyDrive/GeoBench/CityLens-Data/...
21,acc2health,fusion,acc2health-fusion-prithvi_rgb_lora-clip_vitb16...,19,0.167151,9.988541e+00,6.845116e+00,9.977094e+01,/content/drive/MyDrive/GeoBench/CityLens-Data/...
23,acc2health,fusion,acc2health-fusion-prithvi_rgb_lora-resnet50-ga...,3,0.161168,1.002436e+01,6.793436e+00,1.004878e+02,/content/drive/MyDrive/GeoBench/CityLens-Data/...
22,acc2health,fusion,acc2health-fusion-prithvi_rgb_lora-clip_vitb16...,13,0.134735,1.018108e+01,6.703846e+00,1.036543e+02,/content/drive/MyDrive/GeoBench/CityLens-Data/...
15,acc2health,satellite,acc2health-satellite-prithvi_rgb_lora-clip_vit...,9,0.390141,9.550184e+00,7.191029e+00,9.120602e+01,/content/drive/MyDrive/GeoBench/CityLens-Data/...
16,acc2health,satellite,acc2health-satellite-prithvi_rgb_lora-clip_vit...,5,0.303444,1.020646e+01,7.174435e+00,1.041718e+02,/content/drive/MyDrive/GeoBench/CityLens-Data/...
17,acc2health,satellite,acc2health-satellite-resnet50_sat-clip_vitb16-...,22,0.212407,1.085295e+01,7.204183e+00,1.177866e+02,/content/drive/MyDrive/GeoBench/CityLens-Data/...
14,acc2health,satellite,acc2health-satellite-dinov2_sat-clip_vitb16-bs...,20,0.098492,1.161133e+01,8.774560e+00,1.348230e+02,/content/drive/MyDrive/GeoBench/CityLens-Data/...
20,acc2health,street,acc2health-street-prithvi_rgb_lora-resnet50-me...,21,0.329908,8.959551e+00,6.307641e+00,8.027356e+01,/content/drive/MyDrive/GeoBench/CityLens-Data/...
19,acc2health,street,acc2health-street-prithvi_rgb_lora-dinov2_vitb...,11,0.009981,1.089032e+01,7.447273e+00,1.185991e+02,/content/drive/MyDrive/GeoBench/CityLens-Data/...
18,acc2health,street,acc2health-street-prithvi_rgb_lora-clip_vitb16...,3,-0.003083,1.096194e+01,7.364541e+00,1.201642e+02,/content/drive/MyDrive/GeoBench/CityLens-Data/...
33,build_height,fusion,build_height-fusion-prithvi_rgb_lora-dinov2_vi...,23,0.872343,2.527444e+00,1.878616e+00,6.387973e+00,/content/drive/MyDrive/GeoBench/CityLens-Data/...
32,build_height,fusion,build_height-fusion-prithvi_rgb_lora-dinov2_vi...,21,0.865288,2.596345e+00,1.978120e+00,6.741007e+00,/content/drive/MyDrive/GeoBench/CityLens-Data/...
34,build_height,fusion,build_height-fusion-prithvi_rgb_lora-resnet50-...,28,0.859323,2.653199e+00,1.970970e+00,7.039464e+00,/content/drive/MyDrive/GeoBench/CityLens-Data/...
35,build_height,fusion,build_height-fusion-prithvi_rgb_lora-resnet50-...,28,0.848417,2.754131e+00,1.984129e+00,7.585238e+00,/content/drive/MyDrive/GeoBench/CityLens-Data/...
26,build_height,satellite,build_height-satellite-prithvi_rgb_lora-clip_v...,11,0.859866,2.612972e+00,1.909996e+00,6.827624e+00,/content/drive/MyDrive/GeoBench/CityLens-Data/...
27,build_height,satellite,build_height-satellite-prithvi_rgb_lora-clip_v...,5,0.832588,2.855989e+00,2.139061e+00,8.156672e+00,/content/drive/MyDrive/GeoBench/CityLens-Data/...
28,build_height,satellite,build_height-satellite-resnet50_sat-clip_vitb1...,26,0.800435,3.118209e+00,2.280582e+00,9.723226e+00,/content/drive/MyDrive/GeoBench/CityLens-Data/...
25,build_height,satellite,build_height-satellite-dinov2_sat-clip_vitb16-...,18,0.679090,3.954163e+00,2.812445e+00,1.563540e+01,/content/drive/MyDrive/GeoBench/CityLens-Data/...
31,build_height,street,build_height-street-prithvi_rgb_lora-resnet50-...,10,0.344813,5.725870e+00,4.524409e+00,3.278558e+01,/content/drive/MyDrive/GeoBench/CityLens-Data/...
30,build_height,street,build_height-street-prithvi_rgb_lora-dinov2_vi...,22,0.337051,5.759690e+00,4.635670e+00,3.317403e+01,/content/drive/MyDrive/GeoBench/CityLens-Data/...
29,build_height,street,build_height-street-prithvi_rgb_lora-clip_vitb...,17,0.233842,6.191818e+00,4.916267e+00,3.833861e+01,/content/drive/MyDrive/GeoBench/CityLens-Data/...
12,gdp,fusion,gdp-fusion-prithvi_rgb_lora-resnet50-gated-mea...,20,0.443721,4.230626e+08,2.311355e+08,1.789819e+17,/content/drive/MyDrive/GeoBench/CityLens-Data/...
11,gdp,fusion,gdp-fusion-prithvi_rgb_lora-dinov2_vitb14-late...,20,0.396610,4.406128e+08,2.436719e+08,1.941396e+17,/content/drive/MyDrive/GeoBench/CityLens-Data/...
13,gdp,fusion,gdp-fusion-prithvi_rgb_lora-resnet50-late-mean...,6,0.371324,4.497504e+08,2.480087e+08,2.022754e+17,/content/drive/MyDrive/GeoBench/CityLens-Data/...
9,gdp,fusion,gdp-fusion-prithvi_rgb_lora-clip_vitb16-late-m...,18,0.344951,4.590870e+08,2.575216e+08,2.107608e+17,/content/drive/MyDrive/GeoBench/CityLens-Data/...
10,gdp,fusion,gdp-fusion-prithvi_rgb_lora-dinov2_vitb14-gate...,2,0.017164,5.623394e+08,3.767478e+08,3.162256e+17,/content/drive/MyDrive/GeoBench/CityLens-Data/...
8,gdp,fusion,gdp-fusion-prithvi_rgb_lora-clip_vitb16-gated-...,18,0.015131,5.629208e+08,3.146711e+08,3.168798e+17,/content/drive/MyDrive/GeoBench/CityLens-Data/...
2,gdp,satellite,gdp-satellite-prithvi_rgb_lora-clip_vitb16-bs8...,14,0.580773,3.314636e+08,1.981141e+08,1.098681e+17,/content/drive/MyDrive/GeoBench/CityLens-Data/...
1,gdp,satellite,gdp-satellite-prithvi_rgb_lora-clip_vitb16-bs8...,10,0.566657,3.369978e+08,1.900666e+08,1.135675e+17,/content/drive/MyDrive/GeoBench/CityLens-Data/...
0,gdp,satellite,gdp-satellite-dinov2_sat-clip_vitb16-bs8-ep20-...,19,0.453492,3.784510e+08,2.328081e+08,1.432252e+17,/content/drive/MyDrive/GeoBench/CityLens-Data/...
3,gdp,satellite,gdp-satellite-prithvi_rgb_lora-clip_vitb16-bs8...,1,0.191194,4.603980e+08,2.626667e+08,2.119663e+17,/content/drive/MyDrive/GeoBench/CityLens-Data/...
4,gdp,satellite,gdp-satellite-resnet50_sat-clip_vitb16-bs8-ep2...,5,-4.004642,1.145243e+09,3.933633e+08,1.311582e+18,/content/drive/MyDrive/GeoBench/CityLens-Data/...
7,gdp,street,gdp-street-prithvi_rgb_lora-resnet50-mean-bs8-...,7,0.362859,4.527680e+08,3.087936e+08,2.049988e+17,/content/drive/MyDrive/GeoBench/CityLens-Data/...
6,gdp,street,gdp-street-prithvi_rgb_lora-dinov2_vitb14-mean...,13,0.034151,5.574588e+08,3.441883e+08,3.107603e+17,/content/drive/MyDrive/GeoBench/CityLens-Data/...
5,gdp,street,gdp-street-prithvi_rgb_lora-clip_vitb16-mean-b...,19,-0.028651,5.752971e+08,3.385135e+08,3.309667e+17,/content/drive/MyDrive/GeoBench/CityLens-Data/...
44,pop,fusion,pop-fusion-prithvi_rgb_lora-resnet50-gated-mea...,4,-0.294189,1.408040e+04,9.459062e+03,1.982577e+08,/content/drive/MyDrive/GeoBench/CityLens-Data/...
42,pop,fusion,pop-fusion-prithvi_rgb_lora-dinov2_vitb14-gate...,1,-0.329123,1.426917e+04,9.221868e+03,2.036092e+08,/content/drive/MyDrive/GeoBench/CityLens-Data/...
45,pop,fusion,pop-fusion-prithvi_rgb_lora-resnet50-late-mean...,4,-0.348694,1.437384e+04,9.479362e+03,2.066073e+08,/content/drive/MyDrive/GeoBench/CityLens-Data/...
43,pop,fusion,pop-fusion-prithvi_rgb_lora-dinov2_vitb14-late...,5,-0.484851,1.508195e+04,9.584518e+03,2.274653e+08,/content/drive/MyDrive/GeoBench/CityLens-Data/...
37,pop,satellite,pop-satellite-prithvi_rgb_lora-clip_vitb16-bs8...,2,-0.032393,2.164125e+04,1.002026e+04,4.683436e+08,/content/drive/MyDrive/GeoBench/CityLens-Data/...
36,pop,satellite,pop-satellite-dinov2_sat-clip_vitb16-bs8-ep5-l...,5,-0.183969,2.317554e+04,1.136306e+04,5.371057e+08,/content/drive/MyDrive/GeoBench/CityLens-Data/...
38,pop,satellite,pop-satellite-resnet50_sat-clip_vitb16-bs8-ep5...,2,-0.266080,2.396572e+04,1.187183e+04,5.743555e+08,/content/drive/MyDrive/GeoBench/CityLens-Data/...
40,pop,street,pop-street-prithvi_rgb_lora-dinov2_vitb14-mean...,2,0.005767,1.234128e+04,9.162268e+03,1.523072e+08,/content/drive/MyDrive/GeoBench/CityLens-Data/...
39,pop,street,pop-street-prithvi_rgb_lora-clip_vitb16-mean-b...,5,-0.305680,1.414277e+04,9.081771e+03,2.000180e+08,/content/drive/MyDrive/GeoBench/CityLens-Data/...
41,pop,street,pop-street-prithvi_rgb_lora-resnet50-mean-bs8-...,2,-0.435197,1.482764e+04,9.242039e+03,2.198588e+08,/content/drive/MyDrive/GeoBench/CityLens-Data/...

Best run per task and branch:

,task,branch,experiment,best_epoch,r2,rmse,mae
0,acc2health,fusion,acc2health-fusion-prithvi_rgb_lora-resnet50-la...,12,0.190886,9.845183e+00,7.096077e+00
1,acc2health,satellite,acc2health-satellite-prithvi_rgb_lora-clip_vit...,9,0.390141,9.550184e+00,7.191029e+00
2,acc2health,street,acc2health-street-prithvi_rgb_lora-resnet50-me...,21,0.329908,8.959551e+00,6.307641e+00
3,build_height,fusion,build_height-fusion-prithvi_rgb_lora-dinov2_vi...,23,0.872343,2.527444e+00,1.878616e+00
4,build_height,satellite,build_height-satellite-prithvi_rgb_lora-clip_v...,11,0.859866,2.612972e+00,1.909996e+00
5,build_height,street,build_height-street-prithvi_rgb_lora-resnet50-...,10,0.344813,5.725870e+00,4.524409e+00
6,gdp,fusion,gdp-fusion-prithvi_rgb_lora-resnet50-gated-mea...,20,0.443721,4.230626e+08,2.311355e+08
7,gdp,satellite,gdp-satellite-prithvi_rgb_lora-clip_vitb16-bs8...,14,0.580773,3.314636e+08,1.981141e+08
8,gdp,street,gdp-street-prithvi_rgb_lora-resnet50-mean-bs8-...,7,0.362859,4.527680e+08,3.087936e+08
9,pop,fusion,pop-fusion-prithvi_rgb_lora-resnet50-gated-mea...,4,-0.294189,1.408040e+04,9.459062e+03
10,pop,satellite,pop-satellite-prithvi_rgb_lora-clip_vitb16-bs8...,2,-0.032393,2.164125e+04,1.002026e+04
11,pop,street,pop-street-prithvi_rgb_lora-dinov2_vitb14-mean...,2,0.005767,1.234128e+04,9.162268e+03

R2 pivot (best per task/branch):

branch          fusion  satellite    street
task
acc2health    0.190886   0.390141  0.329908
build_height  0.872343   0.859866  0.344813
gdp           0.443721   0.580773  0.362859
pop          -0.294189  -0.032393  0.005767

In [7]:
from pathlib import Path
import json
import pandas as pd

RESULTS_ROOT = Path("/content/drive/MyDrive/GeoBench/CityLens-Data/CityLens-data/Results/global_learned")
TASKS = ["gdp", "acc2health", "build_height", "pop"]
BRANCHES = ["satellite", "street", "fusion"]

def load_metrics(exp_dir: Path):
    mp = exp_dir / "metrics.json"
    if not mp.exists():
        return None
    d = json.loads(mp.read_text())
    return {
        "best_epoch": d.get("best_epoch"),
        "r2": d.get("r2"),
        "rmse": d.get("rmse"),
        "mae": d.get("mae"),
        "mse": d.get("mse"),
    }

rows = []
for t in TASKS:
    task_root = RESULTS_ROOT / t
    if not task_root.exists():
        continue
    for exp in task_root.iterdir():
        if not exp.is_dir():
            continue
        name = exp.name
        branch = None
        for b in BRANCHES:
            if f"{t}-{b}-" in name:
                branch = b
                break
        if branch is None:
            continue
        m = load_metrics(exp)
        if m is None:
            continue
        rows.append({
            "task": t,
            "branch": branch,
            "experiment": name,
            **m,
            "path": str(exp),
        })

df = pd.DataFrame(rows)
if df.empty:
    print("No run metrics found.")
else:
    df = df.sort_values(["task", "branch", "r2"], ascending=[True, True, False])
    display(df)

    best = df.groupby(["task", "branch"], as_index=False).first()
    print("\nBest run per task/branch:")
    display(best[["task","branch","experiment","best_epoch","r2","rmse","mae"]])

    print("\nR2 pivot (best per task/branch):")
    display(best.pivot(index="task", columns="branch", values="r2"))

    # optional: best model token parsed from experiment name
    def parse_model(exp_name, task, branch):
        p = exp_name.replace(f"{task}-{branch}-", "")
        # rough extraction before "-mean-" or "-clip_vitb16-" naming chunk
        return p.split("-mean-")[0].split("-clip_vitb16-")[0]
    best["model_guess"] = best.apply(lambda r: parse_model(r["experiment"], r["task"], r["branch"]), axis=1)
    print("\nBest model guess per task/branch:")
    display(best[["task","branch","model_guess","r2"]])

,task,branch,experiment,best_epoch,r2,rmse,mae,mse,path
23,acc2health,fusion,acc2health-fusion-prithvi_rgb_lora-resnet50-la...,12,0.190886,9.845183e+00,7.096077e+00,9.692764e+01,/content/drive/MyDrive/GeoBench/CityLens-Data/...
22,acc2health,fusion,acc2health-fusion-prithvi_rgb_lora-clip_vitb16...,19,0.167151,9.988541e+00,6.845116e+00,9.977094e+01,/content/drive/MyDrive/GeoBench/CityLens-Data/...
24,acc2health,fusion,acc2health-fusion-prithvi_rgb_lora-resnet50-ga...,3,0.161168,1.002436e+01,6.793436e+00,1.004878e+02,/content/drive/MyDrive/GeoBench/CityLens-Data/...
21,acc2health,fusion,acc2health-fusion-prithvi_rgb_lora-clip_vitb16...,13,0.134735,1.018108e+01,6.703846e+00,1.036543e+02,/content/drive/MyDrive/GeoBench/CityLens-Data/...
15,acc2health,satellite,acc2health-satellite-prithvi_rgb_lora-clip_vit...,9,0.390141,9.550184e+00,7.191029e+00,9.120602e+01,/content/drive/MyDrive/GeoBench/CityLens-Data/...
14,acc2health,satellite,acc2health-satellite-prithvi_rgb_lora-clip_vit...,5,0.303444,1.020646e+01,7.174435e+00,1.041718e+02,/content/drive/MyDrive/GeoBench/CityLens-Data/...
17,acc2health,satellite,acc2health-satellite-resnet50_sat-clip_vitb16-...,22,0.212407,1.085295e+01,7.204183e+00,1.177866e+02,/content/drive/MyDrive/GeoBench/CityLens-Data/...
16,acc2health,satellite,acc2health-satellite-dinov2_sat-clip_vitb16-bs...,20,0.098492,1.161133e+01,8.774560e+00,1.348230e+02,/content/drive/MyDrive/GeoBench/CityLens-Data/...
19,acc2health,street,acc2health-street-prithvi_rgb_lora-resnet50-me...,21,0.329908,8.959551e+00,6.307641e+00,8.027356e+01,/content/drive/MyDrive/GeoBench/CityLens-Data/...
20,acc2health,street,acc2health-street-prithvi_rgb_lora-dinov2_vitb...,11,0.009981,1.089032e+01,7.447273e+00,1.185991e+02,/content/drive/MyDrive/GeoBench/CityLens-Data/...
18,acc2health,street,acc2health-street-prithvi_rgb_lora-clip_vitb16...,3,-0.003083,1.096194e+01,7.364541e+00,1.201642e+02,/content/drive/MyDrive/GeoBench/CityLens-Data/...
34,build_height,fusion,build_height-fusion-prithvi_rgb_lora-dinov2_vi...,23,0.872343,2.527444e+00,1.878616e+00,6.387973e+00,/content/drive/MyDrive/GeoBench/CityLens-Data/...
35,build_height,fusion,build_height-fusion-prithvi_rgb_lora-dinov2_vi...,21,0.865288,2.596345e+00,1.978120e+00,6.741007e+00,/content/drive/MyDrive/GeoBench/CityLens-Data/...
33,build_height,fusion,build_height-fusion-prithvi_rgb_lora-resnet50-...,28,0.859323,2.653199e+00,1.970970e+00,7.039464e+00,/content/drive/MyDrive/GeoBench/CityLens-Data/...
32,build_height,fusion,build_height-fusion-prithvi_rgb_lora-resnet50-...,28,0.848417,2.754131e+00,1.984129e+00,7.585238e+00,/content/drive/MyDrive/GeoBench/CityLens-Data/...
26,build_height,satellite,build_height-satellite-prithvi_rgb_lora-clip_v...,11,0.859866,2.612972e+00,1.909996e+00,6.827624e+00,/content/drive/MyDrive/GeoBench/CityLens-Data/...
25,build_height,satellite,build_height-satellite-prithvi_rgb_lora-clip_v...,5,0.832588,2.855989e+00,2.139061e+00,8.156672e+00,/content/drive/MyDrive/GeoBench/CityLens-Data/...
28,build_height,satellite,build_height-satellite-resnet50_sat-clip_vitb1...,26,0.800435,3.118209e+00,2.280582e+00,9.723226e+00,/content/drive/MyDrive/GeoBench/CityLens-Data/...
27,build_height,satellite,build_height-satellite-dinov2_sat-clip_vitb16-...,18,0.679090,3.954163e+00,2.812445e+00,1.563540e+01,/content/drive/MyDrive/GeoBench/CityLens-Data/...
30,build_height,street,build_height-street-prithvi_rgb_lora-resnet50-...,10,0.344813,5.725870e+00,4.524409e+00,3.278558e+01,/content/drive/MyDrive/GeoBench/CityLens-Data/...
31,build_height,street,build_height-street-prithvi_rgb_lora-dinov2_vi...,22,0.337051,5.759690e+00,4.635670e+00,3.317403e+01,/content/drive/MyDrive/GeoBench/CityLens-Data/...
29,build_height,street,build_height-street-prithvi_rgb_lora-clip_vitb...,17,0.233842,6.191818e+00,4.916267e+00,3.833861e+01,/content/drive/MyDrive/GeoBench/CityLens-Data/...
11,gdp,fusion,gdp-fusion-prithvi_rgb_lora-resnet50-gated-mea...,20,0.443721,4.230626e+08,2.311355e+08,1.789819e+17,/content/drive/MyDrive/GeoBench/CityLens-Data/...
12,gdp,fusion,gdp-fusion-prithvi_rgb_lora-dinov2_vitb14-late...,20,0.396610,4.406128e+08,2.436719e+08,1.941396e+17,/content/drive/MyDrive/GeoBench/CityLens-Data/...
10,gdp,fusion,gdp-fusion-prithvi_rgb_lora-resnet50-late-mean...,6,0.371324,4.497504e+08,2.480087e+08,2.022754e+17,/content/drive/MyDrive/GeoBench/CityLens-Data/...
8,gdp,fusion,gdp-fusion-prithvi_rgb_lora-clip_vitb16-late-m...,18,0.344951,4.590870e+08,2.575216e+08,2.107608e+17,/content/drive/MyDrive/GeoBench/CityLens-Data/...
13,gdp,fusion,gdp-fusion-prithvi_rgb_lora-dinov2_vitb14-gate...,2,0.017164,5.623394e+08,3.767478e+08,3.162256e+17,/content/drive/MyDrive/GeoBench/CityLens-Data/...
9,gdp,fusion,gdp-fusion-prithvi_rgb_lora-clip_vitb16-gated-...,18,0.015131,5.629208e+08,3.146711e+08,3.168798e+17,/content/drive/MyDrive/GeoBench/CityLens-Data/...
2,gdp,satellite,gdp-satellite-prithvi_rgb_lora-clip_vitb16-bs8...,14,0.580773,3.314636e+08,1.981141e+08,1.098681e+17,/content/drive/MyDrive/GeoBench/CityLens-Data/...
1,gdp,satellite,gdp-satellite-prithvi_rgb_lora-clip_vitb16-bs8...,10,0.566657,3.369978e+08,1.900666e+08,1.135675e+17,/content/drive/MyDrive/GeoBench/CityLens-Data/...
3,gdp,satellite,gdp-satellite-dinov2_sat-clip_vitb16-bs8-ep20-...,19,0.453492,3.784510e+08,2.328081e+08,1.432252e+17,/content/drive/MyDrive/GeoBench/CityLens-Data/...
0,gdp,satellite,gdp-satellite-prithvi_rgb_lora-clip_vitb16-bs8...,1,0.191194,4.603980e+08,2.626667e+08,2.119663e+17,/content/drive/MyDrive/GeoBench/CityLens-Data/...
4,gdp,satellite,gdp-satellite-resnet50_sat-clip_vitb16-bs8-ep2...,5,-4.004642,1.145243e+09,3.933633e+08,1.311582e+18,/content/drive/MyDrive/GeoBench/CityLens-Data/...
6,gdp,street,gdp-street-prithvi_rgb_lora-resnet50-mean-bs8-...,7,0.362859,4.527680e+08,3.087936e+08,2.049988e+17,/content/drive/MyDrive/GeoBench/CityLens-Data/...
7,gdp,street,gdp-street-prithvi_rgb_lora-dinov2_vitb14-mean...,13,0.034151,5.574588e+08,3.441883e+08,3.107603e+17,/content/drive/MyDrive/GeoBench/CityLens-Data/...
5,gdp,street,gdp-street-prithvi_rgb_lora-clip_vitb16-mean-b...,19,-0.028651,5.752971e+08,3.385135e+08,3.309667e+17,/content/drive/MyDrive/GeoBench/CityLens-Data/...
43,pop,fusion,pop-fusion-prithvi_rgb_lora-resnet50-gated-mea...,4,-0.294189,1.408040e+04,9.459062e+03,1.982577e+08,/content/drive/MyDrive/GeoBench/CityLens-Data/...
45,pop,fusion,pop-fusion-prithvi_rgb_lora-dinov2_vitb14-gate...,1,-0.329123,1.426917e+04,9.221868e+03,2.036092e+08,/content/drive/MyDrive/GeoBench/CityLens-Data/...
42,pop,fusion,pop-fusion-prithvi_rgb_lora-resnet50-late-mean...,4,-0.348694,1.437384e+04,9.479362e+03,2.066073e+08,/content/drive/MyDrive/GeoBench/CityLens-Data/...
44,pop,fusion,pop-fusion-prithvi_rgb_lora-dinov2_vitb14-late...,5,-0.484851,1.508195e+04,9.584518e+03,2.274653e+08,/content/drive/MyDrive/GeoBench/CityLens-Data/...
36,pop,satellite,pop-satellite-prithvi_rgb_lora-clip_vitb16-bs8...,2,-0.032393,2.164125e+04,1.002026e+04,4.683436e+08,/content/drive/MyDrive/GeoBench/CityLens-Data/...
37,pop,satellite,pop-satellite-dinov2_sat-clip_vitb16-bs8-ep5-l...,5,-0.183969,2.317554e+04,1.136306e+04,5.371057e+08,/content/drive/MyDrive/GeoBench/CityLens-Data/...
38,pop,satellite,pop-satellite-resnet50_sat-clip_vitb16-bs8-ep5...,2,-0.266080,2.396572e+04,1.187183e+04,5.743555e+08,/content/drive/MyDrive/GeoBench/CityLens-Data/...
41,pop,street,pop-street-prithvi_rgb_lora-dinov2_vitb14-mean...,2,0.005767,1.234128e+04,9.162268e+03,1.523072e+08,/content/drive/MyDrive/GeoBench/CityLens-Data/...
39,pop,street,pop-street-prithvi_rgb_lora-clip_vitb16-mean-b...,5,-0.305680,1.414277e+04,9.081771e+03,2.000180e+08,/content/drive/MyDrive/GeoBench/CityLens-Data/...
40,pop,street,pop-street-prithvi_rgb_lora-resnet50-mean-bs8-...,2,-0.435197,1.482764e+04,9.242039e+03,2.198588e+08,/content/drive/MyDrive/GeoBench/CityLens-Data/...

Best run per task/branch:

,task,branch,experiment,best_epoch,r2,rmse,mae
0,acc2health,fusion,acc2health-fusion-prithvi_rgb_lora-resnet50-la...,12,0.190886,9.845183e+00,7.096077e+00
1,acc2health,satellite,acc2health-satellite-prithvi_rgb_lora-clip_vit...,9,0.390141,9.550184e+00,7.191029e+00
2,acc2health,street,acc2health-street-prithvi_rgb_lora-resnet50-me...,21,0.329908,8.959551e+00,6.307641e+00
3,build_height,fusion,build_height-fusion-prithvi_rgb_lora-dinov2_vi...,23,0.872343,2.527444e+00,1.878616e+00
4,build_height,satellite,build_height-satellite-prithvi_rgb_lora-clip_v...,11,0.859866,2.612972e+00,1.909996e+00
5,build_height,street,build_height-street-prithvi_rgb_lora-resnet50-...,10,0.344813,5.725870e+00,4.524409e+00
6,gdp,fusion,gdp-fusion-prithvi_rgb_lora-resnet50-gated-mea...,20,0.443721,4.230626e+08,2.311355e+08
7,gdp,satellite,gdp-satellite-prithvi_rgb_lora-clip_vitb16-bs8...,14,0.580773,3.314636e+08,1.981141e+08
8,gdp,street,gdp-street-prithvi_rgb_lora-resnet50-mean-bs8-...,7,0.362859,4.527680e+08,3.087936e+08
9,pop,fusion,pop-fusion-prithvi_rgb_lora-resnet50-gated-mea...,4,-0.294189,1.408040e+04,9.459062e+03
10,pop,satellite,pop-satellite-prithvi_rgb_lora-clip_vitb16-bs8...,2,-0.032393,2.164125e+04,1.002026e+04
11,pop,street,pop-street-prithvi_rgb_lora-dinov2_vitb14-mean...,2,0.005767,1.234128e+04,9.162268e+03

R2 pivot (best per task/branch):

branch          fusion  satellite    street
task
acc2health    0.190886   0.390141  0.329908
build_height  0.872343   0.859866  0.344813
gdp           0.443721   0.580773  0.362859
pop          -0.294189  -0.032393  0.005767

Best model guess per task/branch:

            task     branch                          model_guess        r2
0     acc2health     fusion       prithvi_rgb_lora-resnet50-late  0.190886
1     acc2health  satellite                     prithvi_rgb_lora  0.390141
2     acc2health     street            prithvi_rgb_lora-resnet50  0.329908
3   build_height     fusion  prithvi_rgb_lora-dinov2_vitb14-late  0.872343
4   build_height  satellite                     prithvi_rgb_lora  0.859866
5   build_height     street            prithvi_rgb_lora-resnet50  0.344813
6            gdp     fusion      prithvi_rgb_lora-resnet50-gated  0.443721
7            gdp  satellite                     prithvi_rgb_lora  0.580773
8            gdp     street            prithvi_rgb_lora-resnet50  0.362859
9            pop     fusion      prithvi_rgb_lora-resnet50-gated -0.294189
10           pop  satellite                     prithvi_rgb_lora -0.032393
11           pop     street       prithvi_rgb_lora-dinov2_vitb14  0.005767

In [8]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1UuodhkBsWojV0Pe-we7ap9bLZMQFvVl19TUCBh754P0/edit#gid=0